In [1]:
import json
import pandas as pd
import re

from bs4 import BeautifulSoup

from langdetect import detect
from langdetect import DetectorFactory

DetectorFactory.seed = 42

with open("../data/raw_ads_2511.json", encoding="utf-8") as f:
    df = pd.DataFrame(json.load(f))

from pathlib import Path

## Datakvalitetskontroll inför städning

In [2]:
print("Antal annonser:", len(df))
print("Unika annons-ID:", df["id"].nunique())

Antal annonser: 6894
Unika annons-ID: 6637

In [3]:
def detect_language(text):
    if not text or not text.strip():
        return "unknown"

    try:
        return detect(text)
    except:
        return "unknown"


# Detektera språk för varje annons
df["language"] = df["description"].apply(detect_language)


# Visa fördelningen av språk
print("Språkfördelning:")
print(df["language"].value_counts())

Språkfördelning:
language
sv         4426
en         2458
unknown       8
fr            2
Name: count, dtype: int64

In [4]:
# Undersöker annonser med språk "unknown"
unknown_ads = df[df["language"] == "unknown"]

for _, row in unknown_ads.iterrows():
    print("=" * 80)
    print("ID:", row["id"])
    print("Titel:", row["title"])
    print("Text:", row["description"])

================================================================================
ID: 29506534
Titel: Teamcenter Solution Architect operations
Text:
================================================================================
ID: 29737028
Titel: Core Network Analyst
Text:
================================================================================
ID: 29817808
Titel: Senior Power BI Specialist - Älmhult
Text:
================================================================================
ID: 30456047
Titel: UI/UX designer
Text:
================================================================================
ID: 30600803
Titel: Dynamics 365 Architect / D365 Solution Architect  16004
Text:
================================================================================
ID: 30854632
Titel: Power BI Consultant (Report Development)
Text:
================================================================================
ID: 30961171
Titel: Senior Data Engineer
Text:
================================================================================
ID: 30983013
Titel: Linux Engineer
Text:

In [5]:
# Identifierar annonser som saknar description eller endast innehåller tomrum
missing_description = df[
    df["description"].isna() |
    df["description"].fillna("").str.strip().eq("")
]

print("Antal annonser utan description:", len(missing_description))

missing_description[
    ["id", "title", "employer", "occupation", "description"]
].head(10)

Antal annonser utan description: 8

,id,title,employer,occupation,description
931,29506534,Teamcenter Solution Architect operations,Hitachi Energy Sweden AB,IT-arkitekt/Lösningsarkitekt,
2424,29737028,Core Network Analyst,Semicon Service Nordic AB,Systemanalytiker/Systemutredare,
2824,29817808,Senior Power BI Specialist - Älmhult,Danda AB,"Affärskonsult, IT",
4475,30456047,UI/UX designer,GreenBay GreenTech Nordic AB,IT-utredare,
4903,30600803,Dynamics 365 Architect / D365 Solution Archite...,Veritaz AB,Enterprise Architect,
5455,30854632,Power BI Consultant (Report Development),Semicon Service Nordic AB,"Verksamhetskonsult, IT",
5777,30961171,Senior Data Engineer,Semicon Service Nordic AB,Data scientist,
5825,30983013,Linux Engineer,Ericsson AB,Systemanalytiker/Systemutredare,

In [6]:
# Identifierar alla rader som tillhör ett duplicerat annons-ID
duplicate_ids = df[
    df["id"].duplicated(keep=False)
].sort_values("id")

print("Antal rader som tillhör ett duplicerat ID:", len(duplicate_ids))
print("Antal duplicerade ID:", duplicate_ids["id"].nunique())

duplicate_ids[
    ["id", "version_id", "title", "employer", "published"]
].head(10)

Antal rader som tillhör ett duplicerat ID: 475
Antal duplicerade ID: 218

,id,version_id,title,employer,published
4,29354585,26008c8a15f486a5b9163029fddd5d7fc3c03cb4,Projektledare,Randstad AB,2025-01-02T10:15:14
5,29354585,f0883b87209ad585259381a396b05e5618ea3d93,Projektledare,Randstad AB,2025-01-02T10:15:14
30,29361752,27b784e84eb1a5703befb304f9f76c3a3c8797db,Teknikansvarig VA till SYSTRA AB i Jönköping,SYSTRA AB,2025-01-07T13:27:42
31,29361752,5fddf1db951f3374f7792910c4f425650ce236e6,Teknikansvarig VA till SYSTRA i Jönköping,SYSTRA AB,2025-01-07T13:27:42
37,29362368,98e4dc9c1ec0419c0fcef0319b64909342df680d,Lösningsarkitekt Nätverksinfrastruktur,Försvarsmakten,2025-01-07T15:11:03
38,29362368,aa58e8f5ebbe56dd9dbc558eea70eb14085eb6de,Lösningsarkitekt Nätverksinfrastruktur,Försvarsmakten,2025-01-07T15:11:03
39,29362443,4acb1a3da382edaf553e92b57524ad381d704d85,Lösningsarkitekt IT-säkerhet,Försvarsmakten,2025-01-07T15:28:34
40,29362443,a335ce8a599380486cb101644acedcc27bef5d5d,Lösningsarkitekt IT-säkerhet,Försvarsmakten,2025-01-07T15:28:34
50,29363892,de9e985fb72fb75014b4c4f676ce7c8bee93db9e,Senior Frontend Engineer,Schibsted Sverige AB,2025-01-08T09:56:04
51,29363892,e3e83d3e1186b260000ba39f70d40dbb5265842d,Frontend Engineer,Schibsted Sverige AB,2025-01-08T09:56:04

In [7]:
# Identifierar HTML-taggar som kan utgöra brus i NLP-analysen
html_pattern = r"<[^>]+>"

html_ads = df[
    df["description"]
    .fillna("")
    .str.contains(html_pattern, regex=True)
]

print("Antal annonser med möjlig HTML:", len(html_ads))

html_ads[
    ["id", "title", "description"]
].head(10)

Antal annonser med möjlig HTML: 3

,id,title,description
4717,30542907,Infrastrukturarkitekt till Växjö kommun,Vill du arbeta med teknik som gör verklig skil...
4966,30622455,Chefsarkitekt | Jula | Skara,Är du redo att forma Julas digitala framtid? D...
5607,30911356,Lösningsarkitekt,Vill du vara med och forma framtidens digitala...

In [8]:
# Regex för att identifiera personnummer
personnummer_pattern = r"\b(?:19|20)?\d{6}[-+ ]?\d{4}\b"

personnummer_count = df["description"].fillna("").str.contains(
    personnummer_pattern, regex=True
).sum()

print("Annonser med möjliga personnummer:", personnummer_count)

Annonser med möjliga personnummer: 0

In [9]:
# Regex för att identifiera epost-adresser
email_pattern = r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b"

email_ads = df[
    df["description"]
    .fillna("")
    .str.contains(email_pattern, regex=True)
]

print("Antal annonser med e-post:", len(email_ads))

Antal annonser med e-post: 0

In [10]:
# Regex för att identifiera möjliga svenska telefonnummer
phone_pattern = r"(?<!\d)(?:\+46|0046|0)[\s-]?(?:\d[\s-]?){7,11}(?!\d)"

phone_ads = df[
    df["description"]
    .fillna("")
    .str.contains(phone_pattern, regex=True)
]

print("Antal annonser med möjliga telefonnummer:", len(phone_ads))

Antal annonser med möjliga telefonnummer: 24

In [11]:
# Kontroll av möjliga telefonnummer före rensning
phone_matches = df["description"].fillna("").str.findall(phone_pattern)

phone_results = df.loc[
    phone_matches.str.len() > 0,
    ["id", "title", "employer"]
].copy()

phone_results["phone_match"] = phone_matches[
    phone_matches.str.len() > 0
].apply(lambda x: ", ".join(x))

phone_results

,id,title,employer,phone_match
186,29386902,IT-arkitekt till domänen Business Common,Vattenfall AB,02-02-2025
187,29386904,IT-arkitekt till domänen Business Common,Vattenfall AB,02-02-2025
188,29386905,IT-arkitekt till domänen Business Common,Vattenfall AB,02-02-2025
427,29422415,Senior Kravanalytiker,Deploja AB,03-02-2025\n
535,29439711,"IT-arkitekt, inriktning Digital Arbetsplats",Länsstyrelsen i Västra Götalands län,000-59 000
1045,29533240,Dataanalytiker sökes av Göteborgs Spårvägar,Göteborgs Stads Kollektivtrafik AB,000-52 000
1865,29663343,IT Specialist till VB Energi,AFRY AB,0240-876 00
1866,29663343,IT Specialist till VB Energi,AFRY AB,0240-876 00
2667,29791470,Senior IT-arkitekt,Deploja AB,01-07-2025
3048,29929162,IT Systemförvaltare – Teknikstöd nät och platt...,Försvarsmakten,0589-40400
3381,30057938,Digitaliseringsstrateg med driv och visioner,Karlskoga kommun,0586-610 55
3536,30112180,Lösningsarkitekt / Teknisk möjliggörare,Universitets- och Högskolerådet,01769-2025
3537,30112194,Senior analytiker och gruppledare,Universitets- och Högskolerådet,01768-2025
4016,30298301,Kravledare,Deploja AB,01-12-2025
4568,30490349,DW Arkitekt,Deploja AB,05-02-2026\n
4813,30570855,Kravanalytiker,Deploja AB,09-02-2026\n
5152,30693508,Lösningsarkitekt,Deploja AB,09-03-2026\n
5426,30835151,Lösningsarkitekt,Deploja AB,08-04-2026\n
6147,31116808,Förändringsorienterad Enterprisearkitekt,Universitets- och högskolerådet,01087-2026
6429,31230562,Systemspecialist med inriktning mobilt kärnnät,Myndigheten för civilt försvar,0771-240 240
6604,31295152,Informationsarkitekt,Folkhälsomyndigheten,01805-2026-2
6605,31295150,Informationsarkitekt,Folkhälsomyndigheten,01805-2026-2
6638,31313337,IT-arkitekt,Folkhälsomyndigheten,02502-2026-2
6639,31313421,IT-arkitekt,Folkhälsomyndigheten,02502-2026-2

In [12]:
# Identifierar möjliga telefonnummer i annonstexterna med hjälp av regex
phone_matches = df["description"].fillna("").str.findall(phone_pattern)

# Hämtar de annonser där minst ett möjligt telefonnummer har hittats
phone_ads = df.loc[
    phone_matches.str.len() > 0
].copy()

# Visar telefonträffarna tillsammans med texten runt träffen för manuell granskning
for _, row in phone_ads.iterrows():
    print("=" * 80)
    print("ID:", row["id"])
    print("Titel:", row["title"])
    print("Träff:", phone_matches.loc[row.name])
    
    description = row["description"]
    
    for match in phone_matches.loc[row.name]:
        start = description.find(match)
        context = description[max(0, start - 100): start + len(match) + 100]
        print("Sammanhang:")
        print(context)

================================================================================
ID: 29386902
Titel: IT-arkitekt till domänen Business Common
Träff: ['02-02-2025']
Sammanhang:
 föräldraledighetstillägg med mera. Läs mer om våra förmåner här
. Välkommen med din ansökan senast 02-02-2025. Urval och intervjuer sker löpande. Vi tar endast emot ansökningar via vår webbplats. Vi är övertyg
================================================================================
ID: 29386904
Titel: IT-arkitekt till domänen Business Common
Träff: ['02-02-2025']
Sammanhang:
 föräldraledighetstillägg med mera. Läs mer om våra förmåner här
. Välkommen med din ansökan senast 02-02-2025. Urval och intervjuer sker löpande. Vi tar endast emot ansökningar via vår webbplats. Vi är övertyg
================================================================================
ID: 29386905
Titel: IT-arkitekt till domänen Business Common
Träff: ['02-02-2025']
Sammanhang:
 föräldraledighetstillägg med mera. Läs mer om våra förmåner här
. Välkommen med din ansökan senast 02-02-2025. Urval och intervjuer sker löpande. Vi tar endast emot ansökningar via vår webbplats. Vi är övertyg
================================================================================
ID: 29422415
Titel: Senior Kravanalytiker
Träff: ['03-02-2025\n']
Sammanhang:
n av in- och utbetalningar• Arbetslivserfarenhet av arbete på statlig myndighetSista ansökningdatum:03-02-2025
Om DeplojaVi sysselsätter idag erfarna konsulter, inom bl.a. Systemutveckling, Test, Arkitektur, IT-
================================================================================
ID: 29439711
Titel: IT-arkitekt, inriktning Digital Arbetsplats
Träff: ['000-59\xa0000 ']
Sammanhang:
in.com/company/lansstyrelsernas-itavdelning

Övrig information
Lönespann för den här tjänsten är 50 000-59 000 kronor. Välkommen med din ansökan! Vi vill gärna att den är på svenska då det är vårt arbetsspråk. A
================================================================================
ID: 29533240
Titel: Dataanalytiker sökes av Göteborgs Spårvägar
Träff: ['000-52 000']
Sammanhang:
ställning. Ett godkänt sådant är krav för anställning. Vårt föreslagna lönespann för tjänsten är 45 000-52 000. Slutgiltig lön beror på hur väl de uppsatta kraven för tjänsten uppfylls. Sex månaders provanställ
================================================================================
ID: 29663343
Titel: IT Specialist till VB Energi
Träff: ['0240-876 00']
Sammanhang:
upplever en god balans mellan arbete och fritid. Placeringsort: Ludvika. Du når dem genom växeln på 0240-876 00. Välkommen med din ansökan senast 16:e maj 2025. Urval och intervjuer kan ske löpande, så vänta int
================================================================================
ID: 29663343
Titel: IT Specialist till VB Energi
Träff: ['0240-876 00']
Sammanhang:
upplever en god balans mellan arbete och fritid. Placeringsort: Ludvika. Du når dem genom växeln på 0240-876 00. Välkommen med din ansökan senast 16:e maj 2025. Urval och intervjuer kan ske löpande, så vänta int
================================================================================
ID: 29791470
Titel: Senior IT-arkitekt
Träff: ['01-07-2025 ']
Sammanhang:
komplexa IT-organisationer, som tex. myndighet eller annan stor organisation. Sista ansökningdatum: 01-07-2025
 Om Deploja  Vi sysselsätter idag erfarna konsulter, inom bl.a. Systemutveckling, Test, Arkitektur,
================================================================================
ID: 29929162
Titel: IT Systemförvaltare – Teknikstöd nät och plattformar
Träff: ['0589-40400 ']
Sammanhang:
efattningen systemanalytiker. Upplysningar om befattningen
Kontakta Anna-Lena Danielsson på telefon 0589-40400 (växel). Din ansökan ska innehålla CV och ansökningsbrev där du motiverar varför du är lämpad för de
================================================================================
ID: 30057938
Titel: Digitaliseringsstrateg med driv och visioner
Träff: ['0586-610 55 ']
Sammanhang:
kningshandlingar i vårt rekryteringssystem. Vänd dig istället till PA-support (HR-avdelningen) tel: 0586-610 55 för vidare hantering. Karlskoga kommun ingår i finskt förvaltningsområde och har därmed ett ansvar f
================================================================================
ID: 30112180
Titel: Lösningsarkitekt / Teknisk möjliggörare
Träff: ['01769-2025']
Sammanhang:
m UHR

Ansök och bli en av oss! Välkommen med din ansökan i form av CV märkt med diarienummer 2.2.1-01769-2025. När du gör din ansökan vill vi att du besvarar ett antal urvalsfrågor. Vi kommer i det första urva
================================================================================
ID: 30112194
Titel: Senior analytiker och gruppledare
Träff: ['01768-2025']
Sammanhang:
m UHR

Ansök och bli en av oss! Välkommen med din ansökan i form av CV märkt med diarienummer 2.2.1-01768-2025. När du gör din ansökan vill vi att du besvarar ett antal urvalsfrågor. Vi kommer i det första urva
================================================================================
ID: 30298301
Titel: Kravledare
Träff: ['01-12-2025 ']
Sammanhang:
 agil metodik • Certifiering enligt IREB, REQB eller motsvarande certifiering Sista ansökningdatum: 01-12-2025
 Om Oss Att jobba på Deploja är något helt annat än att arbeta på ett vanligt konsultbolag – och de
================================================================================
ID: 30490349
Titel: DW Arkitekt
Träff: ['05-02-2026\n']
Sammanhang:
ntlig sektor
Meriterande att ha tidigare erfarenhet av SAS 9.4 och SAS Viya
 Sista ansökningdatum: 05-02-2026

Om Oss Att jobba på Deploja är något helt annat än att arbeta på ett vanligt konsultbolag – och det
================================================================================
ID: 30570855
Titel: Kravanalytiker
Träff: ['09-02-2026\n']
Sammanhang:
rags- eller projektledare
• Certifiering i agila metoder, SAFe eller Scrum

Sista ansökningdatum: 09-02-2026

 Om Oss Att jobba på Deploja är något helt annat än att arbeta på ett vanligt konsultbolag – och de
================================================================================
ID: 30693508
Titel: Lösningsarkitekt
Träff: ['09-03-2026\n']
Sammanhang:
arbetare
• Erfarenhet av att designa och implementera en Elastic ECE lösning
Sista ansökningdatum: 09-03-2026

 Om Oss Att jobba på Deploja är något helt annat än att arbeta på ett vanligt konsultbolag – och de
================================================================================
ID: 30835151
Titel: Lösningsarkitekt
Träff: ['08-04-2026\n']
Sammanhang:
arbetare
• Erfarenhet av att designa och implementera en Elastic ECE lösning
Sista ansökningdatum: 08-04-2026

Vi erbjuder dig följande, Valet är ditt! 🚀 Spännande uppdrag hos våra många kunder. Vi fokuserar på
================================================================================
ID: 31116808
Titel: Förändringsorienterad Enterprisearkitekt
Träff: ['01087-2026']
Sammanhang:
 Välkommen med din ansökan i form av personligt brev och CV på svenska märkt med diarienummer 2.2.1-01087-2026. När du gör din ansökan vill vi att du besvarar ett antal urvalsfrågor. Vi kommer i det första urva
================================================================================
ID: 31230562
Titel: Systemspecialist med inriktning mobilt kärnnät
Träff: ['0771-240\xa0240']
Sammanhang:
nisation, förmåner och hur det är att arbeta hos oss
Vill du veta mer? Samtliga nås via växelnummer 0771-240 240. Välkommen med din ansökan senast den 17 augusti 2026.
================================================================================
ID: 31295152
Titel: Informationsarkitekt
Träff: ['01805-2026-2']
Sammanhang:
e personuppgifter. Ansök senast 2026-08-17 via myndighetens webbplats. Arbetsgivarens diarienummer: 01805-2026-2.1.1
================================================================================
ID: 31295150
Titel: Informationsarkitekt
Träff: ['01805-2026-2']
Sammanhang:
e personuppgifter. Ansök senast 2026-08-17 via myndighetens webbplats. Arbetsgivarens diarienummer: 01805-2026-2.1.1
================================================================================
ID: 31313337
Titel: IT-arkitekt
Träff: ['02502-2026-2']
Sammanhang:
e personuppgifter. Ansök senast 2026-08-24 via myndighetens webbplats. Arbetsgivarens diarienummer: 02502-2026-2.1.1
================================================================================
ID: 31313421
Titel: IT-arkitekt
Träff: ['02502-2026-2']
Sammanhang:
e personuppgifter. Ansök senast 2026-08-24 via myndighetens webbplats. Arbetsgivarens diarienummer: 02502-2026-2.1.1

## Cleaning

In [13]:
print("Antal annonser före rensning:", len(df))


# Behåll endast svenska annonser
df_clean = df[df["language"] == "sv"].copy()

print("Antal svenska annonser:", len(df_clean))

Antal annonser före rensning: 6894
Antal svenska annonser: 4426

In [14]:
# Ta bort dubbletter baserat på annons-ID
antal_fore_dubblettrensning = len(df_clean)

df_clean = df_clean.drop_duplicates(
    subset="id",
    keep="first"
).copy()

antal_efter_dubblettrensning = len(df_clean)

print("Dubblettrensning:")
print("Antal annonser före dubblettrensning:", antal_fore_dubblettrensning)
print("Antal annonser efter dubblettrensning:", antal_efter_dubblettrensning)
print("Antal borttagna dubbletter:", 
      antal_fore_dubblettrensning - antal_efter_dubblettrensning)

Dubblettrensning:
Antal annonser före dubblettrensning: 4426
Antal annonser efter dubblettrensning: 4266
Antal borttagna dubbletter: 160

In [15]:
# Identifierar annonser som saknar annonstext
missing_description = df_clean[
    df_clean["description"].isna() |
    df_clean["description"].fillna("").str.strip().eq("")
]

print("Annonser utan description efter rensning:", len(missing_description))

Annonser utan description efter rensning: 0

In [16]:
# Kontrollerar om möjliga telefonnummer fortfarande finns kvar efter städning
phone_ads_after_duplicates = df_clean[
    df_clean["description"]
    .fillna("")
    .str.contains(phone_pattern, regex=True)
]

print(
    "Annonser med möjlig telefonträff efter rensning:",
    len(phone_ads_after_duplicates)
)

Annonser med möjlig telefonträff efter rensning: 23

In [17]:
# Ersätter verifierade telefonnummer med neutral markör 
def clean_phone_numbers(text):
    if pd.isna(text):
        return text
    
    return re.sub(phone_pattern, "[PHONE]", text)


df_clean["description"] = df_clean["description"].apply(clean_phone_numbers)


phone_matches_clean = df_clean["description"].fillna("").str.findall(phone_pattern)

print(
    "Antal möjliga telefonträffar efter rensning:",
    phone_matches_clean.str.len().sum()
)

Antal möjliga telefonträffar efter rensning: 0

In [18]:
# Räknar hur många telefonnummer som ersattes med [PHONE]
phone_replacements = df_clean["description"].fillna("").str.count(r"\[PHONE\]").sum()

print("Antal ersatta telefonnummer:", phone_replacements)

Antal ersatta telefonnummer: 23

In [19]:
# Kontrollerar om några HTML-taggar fortfarande finns kvar efter cleaning
html_ads = df_clean[
    df_clean["description"]
    .fillna("")
    .str.contains(html_pattern, regex=True)
]

print("Antal HTML-annonser efter rensning:", len(html_ads))

Antal HTML-annonser efter rensning: 3

In [20]:
# Visar annonser med kvarvarande HTML för manuell kontroll
for _, row in html_ads.iterrows():
    print("=" * 80)
    print("ID:", row["id"])
    print("Titel:", row["title"])
    print(row["description"])

================================================================================
ID: 30542907
Titel: Infrastrukturarkitekt till Växjö kommun
Vill du arbeta med teknik som gör verklig skillnad? Hos oss får du chansen att påverka utvecklingen av en hel kommun, där smarta digitala lösningar bidrar till en enklare, tryggare och mer hållbar vardag för invånare, företag och besökare. Nu söker vi en infrastrukturarkitekt som vill vara en nyckelspelare i vår tekniska utvecklingsresa och som motiveras av att arbeta i ett komplext och samhällsviktigt IT‑landskap. Växjö kommun är Kronobergs största arbetsgivare och varje dag arbetar vi tillsammans för framtidens samhälle. <img src="https://sae3ndp007.blob.core.windows.net/swe/71d22a21-1a8c-479b-8fac-9af5f5be811b.jpg">


Om rollen
Som infrastrukturarkitekt blir du en del av vårt team Arkitektur & Utveckling, tillsammans med 12 kollegor inom infrastruktur-, nät- och lösningsarkitektur samt systemutveckling. Här får du en central roll i att forma vår tekniska riktning och skapa robusta och säkra lösningar. Du får arbeta i en miljö med engagerade kollegor och möjlighet att verkligen påverka. Rollen kombinerar strategiskt arbete, med utveckling på konceptnivå och problemlösning. Det här är rätt roll för dig som gillar diskussioner, förändring, driv och att vara en nyckelperson i dialogen mellan teknik och verksamhet. Dina huvudsakliga uppdrag:
Driva den långsiktiga utvecklingen av vår infrastruktur och bidra till vår arkitekturvision. Designa genomtänkta, säkra och hållbara infrastrukturlösningar som möter verksamhetens behov. Omsätta komplexa behov till praktiska och välfungerande tekniska lösningar. Vara rådgivare och bollplank i både pågående projekt och strategiska initiativ. Skapa struktur, planer, Roadmaps och tydliga riktningar för infrastrukturen. Arbeta nära andra arkitekter, systemtekniker och tjänsteansvariga

Kvalifikationer
Vi söker en nyfiken, analytisk och lösningsorienterad person som vill vara med att utveckla hållbara och effektiva lösningar med verklig nytta för verksamheten. Du har en bred teknisk kompetens, en förmåga att kombinera strategiskt tänkande med operativt arbete nära verksamheten. Du tar stort ansvar, arbetar relationsskapande och serviceinriktat, och bidrar aktivt till goda samarbeten och en positiv arbetsmiljö. Som lagspelare delar du med dig av din kunskap och stöttar kollegor. Du har dessutom ett starkt intresse för ny teknik och ser lärande och omvärldsbevakning som en naturlig del i din utveckling. Vi tror att du har:
Flerårig erfarenhet av Microsoftbaserad infrastruktur och Azure, Back-up, SQL etc
En bred teknisk förståelse för infrastrukturella helheter och gärna i större organisationer
Erfarenhet av att arbeta i komplexa leveranser där samarbete är avgörande
Förmåga att designa, förklara och visualisera tekniska lösningar på ett pedagogiskt sätt
God kommunikativ förmåga på svenska i både tal och skrift
Ett strukturerat och kvalitetsfokuserat arbetssätt

Om Växjö kommun
Hos oss får du en trygg arbetsgivare som värnar om balans i livet, stabilitet och långsiktig utveckling. Vi erbjuder både trygghet och möjlighet att växa samtidigt som du får bidra till ett samhällsviktigt uppdrag. Tillsammans bygger vi framtidens Växjö, en hållbar morgondag och en attraktiv kommun att bo, leva och verka i. Det innebär ett arbete där vi utmanar oss att tänka nytt, lära och utvecklas med varandra. Anställning: Tillsvidare, heltid
 Tillträde: Snarast eller enligt överenskommelse
Kontakt och ansökan
I denna rekrytering samarbetar vi med Experis. Vi arbetar med löpande urval - vänta inte med att söka!
================================================================================
ID: 30622455
Titel: Chefsarkitekt | Jula | Skara
Är du redo att forma Julas digitala framtid? Du kommer definiera och leda den övergripande arkitekturen, koppla strategi till praktisk realisering och säkerställa att de tekniska lösningarna skapar långsiktigt värde för verksamheten. Här får du möjlighet att kombinera strategiskt ansvar med operativt genomförande i en dynamisk och expansiv detaljhandelsmiljö. Läs om tjänsten här! Under slutet av 2025 påbörjades förberedelser för ett större transformationsprogram där hela systemlandskapet utvärderas för att säkerställa hållbara och framtidssäkra investeringar. Fokus ligger på plattformar med syfte att stödja Julas kärnverksamhet inom retail och med en riktning mot molnarkitektur. I denna resa söker vi en Chefsarkitekt med en central och strategisk roll i Julas fortsatta digitala utveckling. Rollen är placerad inom funktionen Transformation & Governance, en del av avdelningen IT & Digital, och du rapporterar till Transformation & Governance Manager. Här får du möjlighet att kombinera strategiskt arbete med praktisk realisering i en verksamhet där arkitektur är en avgörande möjliggörare för affären. Om rollen
 Som Chefsarkitekt ansvarar du för att definiera, utveckla och förvalta Julas övergripande arkitekturprinciper och målarkitektur. Du har ägandeskap för den långsiktiga arkitekturella riktningen och säkerställer att den kontinuerligt vidareutvecklas i takt med verksamhetens behov. Rollen innebär inget personalansvar, men du leder strategiskt arkitekturarbetet inom koncernen och samordnar frågor kring arkitektur för att säkerställa att tekniska lösningar stödjer verksamhetens långsiktiga mål samt uppfyller krav på säkerhet, kostnadseffektivitet, skalbarhet och hållbarhet. Ditt uppdrag
 I rollen tar du fram och leder en arkitekturroadmap som kopplar samman initiativ, prioriteringar och realiseringssteg över tid. Under de första 12-18 månaderna förväntas du etablera en framtidssäker målarkitektur med tillhörande roadmap, definiera en tydlig strategi för hur lokala system ska kombineras med molntjänster samt ta fram en plan för hantering och successiv avveckling av teknisk skuld. Du implementerar arkitektoniska best practices med ett pragmatiskt förhållningssätt och säkerställer välfungerande processer, forum och arbetssätt inom arkitekturområdet. Samtidigt stödjer du realiseringen av den arkitektoniska målbilden och bidrar med erfarenhet i både strategiska och operativa faser. Nära samverkan med lösningsarkitekter och arkitekter inom infrastruktur kommer vara avgörande för att lyckas med uppdraget. <img src="https://sae3ndp007.blob.core.windows.net/swe/4a25c81c-d3af-488f-ae26-09e9a6a511bd.jpg">

Vem är du? Vi söker dig som är strategisk, helhetstänkande och trygg i att navigera i komplexa miljöer. Du kan skapa och kommunicera en tydlig arkitekturvision som förstås av både tekniska och icke-tekniska intressenter, samtidigt som du är hands-on när det krävs för att säkerställa framdrift i realiseringen av arkitekturella beslut. Du har gedigen kunskap inom integrationsmönster, informationsmodellering, säkerhetsarkitektur och systemdesign, samt en stark analytisk förmåga att balansera teknik, risk, kostnad och affärsnytta. Som person är du kommunikativ, pedagogisk och förtroendeskapande med ett ledarskap som engagerar och skapar samsyn. Du är lyhörd och samarbetsorienterad, men tydlig i ditt beslutsfattande. Utbildning och erfarenhet
 Du har minst fem års erfarenhet inom IT-arkitektur, varav flera år i ledande eller samordnande roller. Du har dokumenterad erfarenhet av att leda arkitekturarbete i komplexa miljöer, gärna inom koncernstrukturer, samt av att driva förändringsarbete inom både verksamhets- och systemarkitektur. Du har arbetat med molnarkitektur, exempelvis Azure som plattform. Erfarenhet från retail, logistikorienterade verksamheter samt implementering av ERP-system är meriterande. Du behärskar svenska och engelska väl i både tal och skrift och trivs i en dynamisk, entreprenöriell och förändringsintensiv miljö. Koncernen är värderingsstyrd och präglas av långsiktighet, entreprenörskap och en tydlig ambition om fortsatt expansion. Gemensamma koncernfunktioner, däribland IT & Digital, har en central roll i att möjliggöra affärsutveckling, innovation och hållbar tillväxt över hela verksamheten. Sista ansökningsdag: 2026-03-22. Varmt välkommen med din ansökan!
================================================================================
ID: 30911356
Titel: Lösningsarkitekt
Vill du vara med och forma framtidens digitala lösningar? Trivs du i komplexa IT‑miljöer, brinner för tydlig och hållbar lösningsdesign och vill arbeta nära både verksamhet och teknik? Då kan detta vara möjligheten för dig! We<skill> söker nu Lösningsarkitekt till vårt kontor i Göteborg/Alingsås! Erbjudande
Vi erbjuder anställning där vi ser dig med en början i ett långsiktigt projekt i rollen som Lösningsarkitekt. Vi erbjuder vidare en skräddarsydd löne- och förmånsmodell där du har möjlighet att välja mellan olika upplägg beroende på var i livet du befinner dig, oavsett val är du med och sätter din löne- och förmånspaketering utifrån dina önskemål. Du blir del i ett konsultbolag med modern prägel där hållbarhet, flexibilitet och inkludering utgör en stor del av kulturen, en möjlighet att påverka och vara del i utvecklande resa framåt. Om intresse finns är även delägarskap i bolaget en möjlighet. Information om uppdraget och rollen
Vår kund har en modern och växande IT‑organisation som består av flera enheter. Här arbetar arkitekter, projektledare, verksamhetsutvecklare och teknikspecialister tillsammans för att skapa effektiva, trygga och långsiktiga digitala lösningar. Nu söker vi en erfaren Lösningsarkitekt som vill bidra till att stärka arkitekturarbetet och driva utvecklingen framåt. Som Lösningsarkitekt blir du en nyckelperson i flera av kundens viktigaste initiativ. Du arbetar i uppdrag som spänner över hela organisationen — både gemensamma verksamhetsprojekt och interna IT‑projekt. Du kommer främst att vara involverad i:

Förstudier


Anskaffningsfaser


Införandeprojekt (särskilt när tidigare lösningsdesign behöver stärkas)


Du arbetar ofta parallellt i flera uppdrag och samverkar med roller som projektledare, business analysts, systemförvaltare, systemtekniker och drifttekniker — både från verksamhet och IT.

In [21]:
# Tar bort HTML-taggar men behåller den synliga texten
def clean_html(text):
    if pd.isna(text):
        return text
    
    return BeautifulSoup(text, "html.parser").get_text(" ", strip=True)


df_clean["description"] = df_clean["description"].apply(clean_html)


html_after = df_clean[
    df_clean["description"]
    .fillna("")
    .str.contains(r"<[^>]+>", regex=True)
]

print("Annonser med HTML efter cleaning:", len(html_after))

Annonser med HTML efter cleaning: 0

In [22]:
# Söker efter kontaktrelaterade fraser för att manuellt kontrollera
# om personnamn eller andra personuppgifter förekommer i anslutning till dessa
contact_pattern = (
    r"(?i)(kontaktperson|kontakt|kontakta|ansvarig|rekryterare|"
    r"rekryteringsansvarig|för frågor|vid frågor|har du frågor)"
)

contact_ads = df_clean[
    df_clean["description"]
    .fillna("")
    .str.contains(contact_pattern, regex=True)
]

print("Annonser med kontaktfraser:", len(contact_ads))

for _, row in contact_ads.head(20).iterrows():
    description = row["description"]
    match = re.search(contact_pattern, description)

    print("=" * 80)
    print("ID:", row["id"])
    print("Titel:", row["title"])

    if match:
        start = match.start()
        end = min(len(description), match.end() + 200)

        print(description[start:end].replace("\n", " "))

/tmp/ipykernel_14515/2175045008.py:11: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  .str.contains(contact_pattern, regex=True)

Annonser med kontaktfraser: 1742
================================================================================
ID: 29354585
Titel: Projektledare
kontaktytor och intressanta utmaningar. Då kan denna tjänst vara något för dig. Beskrivning av gruppen, En hel kommun är beroende av att vi genomför vårt uppdrag i allt från naturnära områden till stadsmiljö
================================================================================
ID: 29355065
Titel: Consultant Manager till ett av våra grymma Dynamics 365 F&SCM-team
kontakt och involveras tidigt i affärerna ur ett resurssättningsperspektiv. Viktigt att poängtera är att vi inte jobbar med resurskonsulter, utan att vi är ett projektkonsultföretag vilket gör att dina medar
================================================================================
ID: 29355172
Titel: Systemspecialist med inriktning IT-infrastruktur till Säkra IT-lösningar
kontakter. Önskar du att arbeta delvis på distans? I den här tjänsten kan det finnas möjlighet att arbeta hemifrån upp till 40 procent av din arbetstid. #LI-Hybrid Intervjuer sker via Skype, preliminärt unde
================================================================================
ID: 29355229
Titel: IT arkitekt / Lösningsarkitekt till energisektorn i Umeå
ansvarig för Lösningsarkitekturteamet. Uppdragsperiod: Uppdraget löper från kontraktstecknande till och med 2025-06-01, med option på förlängning upp till sex (6) månader, dock som längst till och med 2025-12
================================================================================
ID: 29355231
Titel: IT arkitekt / Lösningsarkitekt till energisektorn i Umeå
ansvarig för Lösningsarkitekturteamet. Uppdragsperiod: Uppdraget löper från kontraktstecknande till och med 2025-06-01, med option på förlängning upp till sex (6) månader, dock som längst till och med 2025-12
================================================================================
ID: 29355214
Titel: IT arkitekt / Lösningsarkitekt till energisektorn i Umeå
ansvarig för Lösningsarkitekturteamet. Uppdragsperiod: Uppdraget löper från kontraktstecknande till och med 2025-06-01, med option på förlängning upp till sex (6) månader, dock som längst till och med 2025-12
================================================================================
ID: 29355216
Titel: IT arkitekt / Lösningsarkitekt till energisektorn i Umeå
ansvarig för Lösningsarkitekturteamet. Uppdragsperiod: Uppdraget löper från kontraktstecknande till och med 2025-06-01, med option på förlängning upp till sex (6) månader, dock som längst till och med 2025-12
================================================================================
ID: 29355312
Titel: IT arkitekt / Lösningsarkitekt till energisektorn i Umeå
ansvarig för Lösningsarkitekturteamet. Uppdragsperiod: Uppdraget löper från kontraktstecknande till och med 2025-06-01, med option på förlängning upp till sex (6) månader, dock som längst till och med 2025-12
================================================================================
ID: 29355346
Titel: IT konsult för bedömning av Microsoft och molntjänster till Umeå Kommun
kontaktperson som tar hand om allt du kan tänkas behöva inför, under och efter uppdraget. Din kontaktperson följer också kontinuerligt upp att du trivs på din arbetsplats och att allt är som det ska. Att vara kons
================================================================================
ID: 29355442
Titel: IT konsult för bedömning av Microsoft och molntjänster till Umeå Kommun
kontaktperson som tar hand om allt du kan tänkas behöva inför, under och efter uppdraget. Din kontaktperson följer också kontinuerligt upp att du trivs på din arbetsplats och att allt är som det ska. Att vara kons
================================================================================
ID: 29355444
Titel: IT konsult för bedömning av Microsoft och molntjänster till Umeå Kommun
kontaktperson som tar hand om allt du kan tänkas behöva inför, under och efter uppdraget. Din kontaktperson följer också kontinuerligt upp att du trivs på din arbetsplats och att allt är som det ska. Att vara kons
================================================================================
ID: 29355465
Titel: IT konsult för bedömning av Microsoft och molntjänster till Umeå Kommun
kontaktperson som tar hand om allt du kan tänkas behöva inför, under och efter uppdraget. Din kontaktperson följer också kontinuerligt upp att du trivs på din arbetsplats och att allt är som det ska. Att vara kons
================================================================================
ID: 29355459
Titel: IT konsult för bedömning av Microsoft och molntjänster till Umeå Kommun
kontaktperson som tar hand om allt du kan tänkas behöva inför, under och efter uppdraget. Din kontaktperson följer också kontinuerligt upp att du trivs på din arbetsplats och att allt är som det ska. Att vara kons
================================================================================
ID: 29355463
Titel: IT konsult för bedömning av Microsoft och molntjänster till Umeå Kommun
kontaktperson som tar hand om allt du kan tänkas behöva inför, under och efter uppdraget. Din kontaktperson följer också kontinuerligt upp att du trivs på din arbetsplats och att allt är som det ska. Att vara kons
================================================================================
ID: 29355488
Titel: IT konsult för bedömning av Microsoft och molntjänster till Umeå Kommun
kontaktperson som tar hand om allt du kan tänkas behöva inför, under och efter uppdraget. Din kontaktperson följer också kontinuerligt upp att du trivs på din arbetsplats och att allt är som det ska. Att vara kons
================================================================================
ID: 29357400
Titel: Infrastructure Specialist till Turnpikes
kontakter och bidra till förbättringar av systemens prestanda och säkerhet. Vi tillämpar löpande urval och kommer plocka ner annonsen när tillräckligt många kandidater har nått slutskedet i rekryteringsproce
================================================================================
ID: 29360138
Titel: Enterprise Architect - Applikation/ Integrationer
rekryteraren vid frågor. Efter inskickad ansökan kommer vi dels anonymisera dina personuppgifter, dels be dig att göra ett par rekryteringstester, innan vi gör en första bedömning. Givetvis får du mer informatio
================================================================================
ID: 29360939
Titel: Senior Enterprise Arkitekt
kontakta ****
================================================================================
ID: 29361752
Titel: Teknikansvarig VA till SYSTRA AB i Jönköping
ansvarig hos oss på SYSTRA har du en central roll i våra projekt där du har det övergripande ansvaret för teknikområdet VA. Du kommer leda den tekniska framdriften inom projekten, samordna med övriga tekniker
================================================================================
ID: 29361776
Titel: Data Engineer
kontakt med oss: **** gärna mer om oss och träffa våra medarbetare på vår karriärsida: https://karriar.accigo.se/

- För att identifiera annonsernas språk användes paketet `langdetect`. Endast annonser som klassificerades som svenska behölls för den fortsatta analysen. De annonser som klassificerades som `unknown` granskades manuellt och visade sig bestå av tomma annonser. Dessa ingår därför inte i den fortsatta kompetensanalysen.

- Vid kontroll av potentiella personuppgifter identifierades inga träffar för e-postadresser eller personnummer.  

- Regexbaserad identifiering av telefonnummer gav 23 möjliga träffar. Dessa granskades manuellt för att bedöma om de utgjorde faktiska telefonnummer.   
Några av träffarna visade sig vara telefonnummer till företagsväxlar. Verifierade telefonnummer, inklusive företagsväxlar, ersätts med `[PHONE]` eftersom de inte är relevanta för kompetensanalysen.

- Förekomst av HTML-taggar kontrollerades med regex. Ett fåtal annonser innehöll HTML-formatering, men mängden var begränsad. HTML-taggarna tas bort eftersom de inte innehåller relevant information för kompetensanalysen och annars kan utgöra brus vid den fortsatta NLP-bearbetningen.

- Som en extra kontroll av personnamn söktes kontaktrelaterade fraser i annonstexterna för att undersöka om man kan hitta personnamn. Vid manuell granskning syntes inga direkta personuppgifter, utan i de fall där sådan information verkar ha funnits var den redan ersatt med `****`.     
Det tyder på att personuppgifter redan har maskerats i materialet som hämtats från JobTech Historical API.

- Regexbaserad identifiering kan användas för strukturerade uppgifter som e-postadresser, telefonnummer och personnummer men är mindre lämplig för att identifiera personnamn. Förekomst av personnamn kommer därför undersökas separat med spaCy NER.

## Identifiering av personnamn med SpaCy

Personuppgifter återfinns vanligen i slutet av annonser i relation till "för fler frågor, kontakta.." eller "rekryterande chef" efterföljt av ett namn. Därför börjar vi med att ladda in texten och tittar på de 300 sista orden i ett urval av annonserna för att se om det finns några personnamn.

In [23]:
print(len(df_clean))

# slumpa 10 annonser och titta på de sista 300 tecknen
sample = df_clean.dropna(subset=["description"]).sample(10, random_state=1)
for _, row in sample.iterrows():
    print(row["id"], "...", row["description"][-300:])
    print("-" * 60)

4266
29928135 ... ta företag och arbetar både nationellt och internationellt. Med baser i Sverige och Spanien erbjuder vi en unik kombination av lokal expertis och global räckvidd. Vårt starka nätverk och djupa branschinsikter gör oss till en självklar partner för företag som vill ligga steget före i sin rekrytering.
------------------------------------------------------------
29692285 ...  abstrahera och förklara komplexa tekniska lösningar på ett lättförståeligt sätt
   Strukturerad och självständig i arbetssättet




Vill du vara med och skapa en lösning som gör verklig skillnad för verksamheten? Välkommen att höra av dig till Soros Consulting med din ansökan eller intresseanmälan.
------------------------------------------------------------
30359337 ... d olika bakgrund. Söker du en tjänst hos oss som omfattas av krigsplacering kommer du få information om det i samband med din anställning. Kommunen har gjort aktiva val i denna rekrytering och vill därför inte bli kontaktade med erbjudanden om annonserings- och rekryteringshjälp/kompetensförmedling.
------------------------------------------------------------
30439170 ... nonsen kan stängas ner innan tjänsten är tillsatt om vi gått över till urval- och intervjufasen. Om du vill kan du även skapa en användare och ladda upp ditt CV och personliga brev. Vi tar tyvärr inte emot ansökningar via mail men har du frågor kring tjänsten är du välkommen att kontakta oss på ****
------------------------------------------------------------
29664582 ... åra säkerhetsrutiner. https://www.migrationsverket.se/Om-Migrationsverket/Vart-uppdrag/Personuppgifter.html


Migrationsverkets rekryteringar sker helt i vår egen eller upphandlade leverantörers regi. Vi ber därför om att inte få telefonsamtal och mejl från rekryteringsföretag och annonsförsäljare.
------------------------------------------------------------
30288245 ... kan göras lååång. Möjligheterna bra nära oändliga. Castra har kontor i Göteborg, Stockholm, Malmö, Linköping, Norrköping, Örebro, Jönköping och Sundsvall. Läs mer om hur det är att jobba hos oss på castra.se/konsulterbjudande/
Har vi lyckats väcka din nyfikenhet? Har vi lyckats väcka din nyfikenhet?
------------------------------------------------------------
31348710 ... äck oändliga möjligheter. Anta utmaningar, skapa smarta innovationer och uppgradera dina förmågor. Det här är en plats för kluriga tänkare, modiga pionjärer och alla däremellan. Tillsammans uppnår vi det extraordinära, var och en tar med sitt unika perspektiv. Varje bidrag räknas. Läs mer om oss här
------------------------------------------------------------
30806543 ...  bifogas, exempelvis utbildningsbevis eller legitimation. Du kommer även få besvara urvalsfrågor. Du som söker jobb och har skyddade personuppgifter ska kontakta rekryterande chef i annonsen som kommer guida dig vidare för en säker ansökningsprocess. Du ska inte ansöka digitalt via ansökningslänken.
------------------------------------------------------------
30536528 ... vård och tjänstepension. Vi är specialiserade inom IT, Teknik, HR, Administration och Ekonomi. Vår målsättning är att vara din personliga samarbetspartner och just därför är det så viktigt för oss att arbeta efter våra kärnvärden där våra ledord är att vara Personliga, Nyskapande och Professionella.
------------------------------------------------------------
29797713 ...  här rekryteringsprocessen kommer att vara på semester periodvis under sommarmånaderna. Svar på frågor och återkoppling kan därför komma att dröja. Skicka in din ansökan, njut av sommaren så hör vi av oss när vi kommit vidare med att läsa om just din erfarenhet och kompetens, senast i augusti månad.
------------------------------------------------------------

Utskrifter visar att inga personuppgifter dyker upp i någon av exemplerna. Kan bero på att det antingen inte finns några personuppgifter alls i exempelannonserna (redan borttagna av JobTech) eller att de finns någon annanstans än i slutet av annonstexten.

### SpaCy pipeline

Skapar en spaCy pipeline där modellen tittar på ett litet urval och på alla entitetstyper, inte bara personer för att identifiera personnamn.

In [24]:
import spacy
from collections import Counter

nlp = spacy.load("sv_core_news_sm", disable=["parser", "lemmatizer"])
print(nlp.get_pipe("ner").labels)       # vilka etiketter finns

sample50 = df_clean.sample(50, random_state=1)

counts = Counter()
per_hits = []                           # (annons-id, träff, var i texten 0-1, omgivande text)

for _, row in sample50.iterrows():
    text = row["description"]
    doc = nlp(text)
    for ent in doc.ents:
        counts[ent.label_] += 1
        if ent.label_ == "PRS":     
            pos = ent.start_char / len(text)
            context = text[max(ent.start_char - 40, 0): ent.end_char + 40].replace("\n", " ")
            per_hits.append((row["id"], ent.text, round(pos, 2), context))

print(counts)
print(len(per_hits), "personträffar")
print(Counter(h[1] for h in per_hits).most_common(30))
for h in per_hits[:30]:
    print(h)

('EVN', 'LOC', 'MSR', 'OBJ', 'ORG', 'PRS', 'TME', 'WRK')
Counter({'LOC': 291, 'ORG': 174, 'PRS': 144, 'TME': 22, 'WRK': 14, 'OBJ': 2, 'MSR': 2, 'EVN': 2})
144 personträffar
[('Kubernetes', 7), ('Castra', 6), ('Van', 4), ('Helsingborgs', 4), ('Sopra Steria', 4), ('Databricks', 3), ('Verifieds', 3), ('workshops', 3), ('Avaron AB', 3), ('Hybrid', 3), ('Data Scientist', 3), ('Enterprise Architecture', 3), ('Erfarenhet', 2), ('Förmåga', 2), ('Manager', 2), ('• Erfarenhet', 2), ('Data Science', 2), ('Ansök', 2), ('API:er', 2), ('Walley', 2), ('LinkedIn', 2), ('Azure Databricks', 2), ('Product Owner', 1), ('Teams', 1), ('Ansvara', 1), ('Excel', 1), ('Vänersborgs', 1), ('Verified Global', 1), ('Contract Lifecycle', 1), ('Team Diamant', 1)]
('29928135', 'Product Owner', 0.0, 'Vi söker en Product Owner inom Communication & Collaboration. Hyb')
('29928135', 'Teams', 0.43, 'ap om Microsoft 365:s samarbetsverktyg (Teams, SharePoint, Outlook, OneDrive m.fl.). ')
('29692285', 'Ansvara', 0.28, 'en Som dataarkitekt kommer du att:      Ansvara för design och teknisk riktning för hel')
('29692285', 'Excel', 0.62, 'torisk kompetens:      Avancerad nivå i Excel    Avancerad erfarenhet av Data & Analy')
('29692285', 'Van', 0.7, 'med simuleringar och prognosmodeller    Van att agera som kommunikativ kravställare')
('29692285', 'Erfarenhet', 0.77, 'tveckling   Meriterande kompetens:      Erfarenhet av Databricks   Personliga egenskaper: ')
('29692285', 'Databricks', 0.78, 'riterande kompetens:      Erfarenhet av Databricks   Personliga egenskaper:      Lösningso')
('29692285', 'Förmåga', 0.81, ' egenskaper:      Lösningsorienterad    Förmåga att abstrahera och förklara komplexa te')
('30359337', 'Vänersborgs', 0.77, 'ter att växa och utvecklas i rollen. Om Vänersborgs kommun  Som medarbetare i Vänersborgs k')
('30439170', 'Verified Global', 0.0, 'Verified Global växer och söker nu en Solution Manager ')
('30439170', 'Manager', 0.01, 'd Global växer och söker nu en Solution Manager till verksamheten i Sverige! Här kommer')
('30439170', 'Verifieds', 0.12, 'a dig vi söker! Information om tjänsten Verifieds resa startade 2012 med fokus på elektro')
('30439170', 'Contract Lifecycle', 0.2, 'systemstöd för antipenningtvätt KYC och Contract Lifecycle Managment. Kontoret i Solna kommer att ')
('30439170', 'Verifieds', 0.36, 'ssen hanteras av Professionals Nord och Verifieds önskemål är att alla frågor kring tjäns')
('30439170', 'Manager', 0.38, 'r kring tjänsten går till **** Solution Manager kommer du att spela en viktig roll i ku')
('30439170', 'Verifieds', 0.58, 'lan och budget Vara en nyckelperson för Verifieds produkter/ tjänster Stödja försäljning ')
('29664582', 'Team Diamant', 0.12, 'det arbetet. Vi har ett dedikerat team, Team Diamant, som ansvarar för våra externa identite')
('29664582', 'Kubernetes', 0.32, 'modern, cloud native plattform byggd på Kubernetes och Docker. Vår arkitektur rör sig mot ')
('29664582', 'Access Management', 0.56, 'et av utveckling inom IAM (Identity and Access Management). - Erfarenhet av produkter som Keycloa')
('29664582', 'Microsoft ADFS', 0.58, '- Erfarenhet av produkter som Keycloak, Microsoft ADFS, Shibboleth  - Kunskap om autentisering')
('29664582', 'Shibboleth', 0.58, 'produkter som Keycloak, Microsoft ADFS, Shibboleth  - Kunskap om autentiseringsprotokoll s')
('30288245', 'Castra', 0.03, 'olagen och vi kan med stolthet säga att Castra är konsultbranschens mest utvecklande a')
('30288245', 'Engineer', 0.09, 'ärna vidare. Rollen I rollen som\xa0DevOps\xa0Engineer kommer du att spela en nyckelroll i att')
('30288245', 'Ansible', 0.18, 'nfrastrukturer med hjälp av verktyg som Ansible, Terraform, eller liknande. Säkerställa')
('30288245', 'Docker', 0.32, ' Erfarenhet av containerteknologier som Docker och Kubernetes. Förståelse för versione')
('30288245', 'Kubernetes', 0.33, ' av containerteknologier som Docker och Kubernetes. Förståelse för versioneringssystem som')
('30288245', 'Azure DevOps Engineer', 0.4, 'jänster (AWS Certified DevOps Engineer, Azure DevOps Engineer, etc.). Erfarenhet av att arbeta i agil')
('30288245', 'Castra', 0.45, 'ästa åt de bästa – vår personalfilosofi Castra är en konsultgrupp inom IT och Manageme')
('30288245', 'Castra', 0.6, 'n det är faktiskt inte vi som sagt det. Castra har sedan 2017 blivit certifierad av Gr')
('30288245', 'Great Place', 0.62, 'ra har sedan 2017 blivit certifierad av Great Place to Work och har de senaste två åren bli')

### Vad resultatet visar

Av de träffar som syns är ingen ett personnamn, vilket tyder på att det flesta träffar faktiskt är falska träffar. 

Noll riktiga namn bland urvalen kan betyda två olika saker:

1. Namnen finns inte i texten, eftersom JobTech tagit bort dem.
2. Namnen finns, men modellen är för dålig på jobbannonser för att hitta dem.

### Litet test

Testar om modellen över huvud taget kan hitta namn i en annons med hjälp av exempeltext.

In [25]:
test_names = [
    "Kontakta rekryterande chef Anna Svensson på telefon 070 123 45 67.",
    "Har du frågor om tjänsten? Hör av dig till Erik Lindqvist.",
    "Fackliga företrädare: Maria Johansson och Karl Andersson.",
    "Vid frågor kontakta Fatima Hassan, rekryterare.",
]

base = df_clean["description"].iloc[0]
for sentence in test_names:
    doc = nlp(base[-300:] + " " + sentence)
    print([(e.text, e.label_) for e in doc.ents if e.start_char >= len(base[-300:])])

[('Anna Svensson', 'PRS')]
[('Erik Lindqvist', 'PRS')]
[('Maria Johansson', 'PRS'), ('Karl Andersson', 'PRS')]
[('Fatima Hassan', 'PRS')]

Modellen hittar testnamnen vilket tyder på att modellen bör kunna identifiera personnamn i annonstexterna, även om flest träffar verkar vara falska.

Testar att köra pipelinen på alla annonser för att säkerställa att inga personnamn har missats att rensas bort.

In [26]:
nlp = spacy.load("sv_core_news_sm", disable=["parser", "lemmatizer"])
print(nlp.get_pipe("ner").labels)       # vilka etiketter finns

counts = Counter()
per_hits = []                           # (annons-id, träff, var i texten 0-1, omgivande text)

for _, row in df_clean.iterrows():
    text = row["description"]
    doc = nlp(text)
    for ent in doc.ents:
        counts[ent.label_] += 1
        if ent.label_ == "PRS":     
            pos = ent.start_char / len(text)
            context = text[max(ent.start_char - 40, 0): ent.end_char + 40].replace("\n", " ")
            per_hits.append((row["id"], ent.text, round(pos, 2), context))

print(counts)
print(len(per_hits), "personträffar")
print(Counter(h[1] for h in per_hits).most_common(30))
for h in per_hits[:30]:
    print(h)

('EVN', 'LOC', 'MSR', 'OBJ', 'ORG', 'PRS', 'TME', 'WRK')
Counter({'LOC': 18075, 'ORG': 13662, 'PRS': 11972, 'TME': 1202, 'WRK': 1143, 'OBJ': 268, 'MSR': 192, 'EVN': 122})
11972 personträffar
[('workshops', 476), ('• Erfarenhet', 437), ('Avaron AB', 379), ('Kubernetes', 264), ('Azure', 218), ('Förmåga', 199), ('Sopra Steria', 193), ('Leda', 179), ('Fellowmind', 147), ('Ansök', 142), ('Intervjuer', 138), ('Enterprise Architect', 115), ('LinkedIn', 105), ('Databricks', 101), ('Castra', 98), ('Java', 93), ('Data Scientist', 88), ('Python', 87), ('Enterprise', 84), ('Erfarenhet', 81), ('Västra Götalandsregionen', 71), ('Trusted Advisor', 63), ('Ansvara', 60), ('Hybrid', 60), ('Kafka', 60), ('Manager', 58), ('Van', 58), ('Delge', 58), ('Sälj', 57), ('Great Place', 56)]
('29354331', 'Acquirer', 0.42, 'nom hela betalcykeln, som ex. Merchant, Acquirer, Issuer, Card schemes och Open Banking.')
('29354331', 'Issuer', 0.43, 'etalcykeln, som ex. Merchant, Acquirer, Issuer, Card schemes och Open Banking. Vi söke')
('29354331', 'Card', 0.43, 'ln, som ex. Merchant, Acquirer, Issuer, Card schemes och Open Banking. Vi söker dig ')
('29354585', 'Sickla Köpkvarter', 0.6, 'derna lokaler i Finntorp, i närheten av Sickla Köpkvarter med goda kommunikationer. För att söka ')
('29355065', 'Better Together', 0.04, 't i våra värderingar – Always personal, Better Together, Serious about fun & Act with courage k')
('29355065', 'Fellowmind', 0.88, 'ntervju, tester och referenstagning. Om Fellowmind Fellowmind är en europeisk marknadsleda')
('29355065', 'Fellowmind', 0.88, 'ster och referenstagning. Om Fellowmind Fellowmind är en europeisk marknadsledare inom dig')
('29355065', 'Modern Workplace', 0.95, 'taanalys och AI, till CRM, intranät och Modern Workplace. Fellowmind är ett internationellt bola')
('29355172', 'Ansvara', 0.27, 'Avancerad felsökning och felavhjälpning Ansvara för systemtester inför driftsättningar ')
('29355172', 'Intervjuer', 0.45, '40 procent av din arbetstid. #LI-Hybrid Intervjuer sker via Skype, preliminärt under vecka')
('29355229', 'Microsoftplattformen', 0.42, 'de Meriterande att ha god erfarenhet av Microsoftplattformen  Du kan avgöra behov och se vad som är ')
('29355231', 'Microsoftplattformen', 0.42, 'de Meriterande att ha god erfarenhet av Microsoftplattformen  Du kan avgöra behov och se vad som är ')
('29355214', 'Microsoftplattformen', 0.42, 'de Meriterande att ha god erfarenhet av Microsoftplattformen  Du kan avgöra behov och se vad som är ')
('29355216', 'Microsoftplattformen', 0.42, 'de Meriterande att ha god erfarenhet av Microsoftplattformen  Du kan avgöra behov och se vad som är ')
('29355312', 'Microsoftplattformen', 0.42, 'de Meriterande att ha god erfarenhet av Microsoftplattformen  Du kan avgöra behov och se vad som är ')
('29355346', 'Entra', 0.23, 'r kan t ex vara M365 for Apps (Office), Entra, Teams, Sharepoint, Copilot, Azure, Fab')
('29355346', 'Teams', 0.24, ' ex vara M365 for Apps (Office), Entra, Teams, Sharepoint, Copilot, Azure, Fabric, On')
('29355346', 'Fabric', 0.24, 'tra, Teams, Sharepoint, Copilot, Azure, Fabric, OneDrive, Defender och Purview – men k')
('29355346', 'Defender', 0.24, 'oint, Copilot, Azure, Fabric, OneDrive, Defender och Purview – men kan komma att justera')
('29355346', 'Purview', 0.25, ', Azure, Fabric, OneDrive, Defender och Purview – men kan komma att justeras utifrån pr')
('29355346', 'Förmåga', 0.47, '-4) Molnbaserade tjänster och tekniker  Förmåga att analysera och kommunicera komplex i')
('29355346', 'Metodik', 0.49, 't sätt med olika typer av intressenter  Metodik: Konsult förväntas använda en riskanaly')
('29355346', 'Workshops', 0.56, 'iteringar, i del 2 innan sommaren 2025. Workshops och presentationer: Planeras i samråd m')
('29355442', 'Entra', 0.23, 'r kan t ex vara M365 for Apps (Office), Entra, Teams, Sharepoint, Copilot, Azure, Fab')
('29355442', 'Teams', 0.24, ' ex vara M365 for Apps (Office), Entra, Teams, Sharepoint, Copilot, Azure, Fabric, On')
('29355442', 'Fabric', 0.24, 'tra, Teams, Sharepoint, Copilot, Azure, Fabric, OneDrive, Defender och Purview – men k')
('29355442', 'Defender', 0.25, 'oint, Copilot, Azure, Fabric, OneDrive, Defender och Purview – men kan komma att justera')
('29355442', 'Purview', 0.25, ', Azure, Fabric, OneDrive, Defender och Purview – men kan komma att justeras utifrån pr')
('29355442', 'Förmåga', 0.47, '-4) Molnbaserade tjänster och tekniker  Förmåga att analysera och kommunicera komplex i')
('29355442', 'Metodik', 0.49, 't sätt med olika typer av intressenter  Metodik: Konsult förväntas använda en riskanaly')

Modellen identifierar 11 972 personträffar, varav majoriteten ser ut att fortfarande vara falska träffar. För att undersöka vidare om det finns några riktiga personnamn så behöver träffarna vidare granskas.

### Filter för att hitta riktiga personnamn

För att försöka identifiera vad som är riktiga personamn bland alla träffar skapar vi filter som sorterar bort det som med säkerhet inte är ett namn för att minska antalet träffar att manuellt granska. 

- Filter 1: ser det ut som ett namn? Riktiga namn är ett till tre ord som alla börjar med stor bokstav och i övrigt har små bokstäver.
- Filter 2: används ordet som ett vanligt ord? Ett vanligt ord som "workshops" eller "solutions" förekommer ofta med liten bokstav, medan ett förnamn som "Anna" gör det nästan aldrig. Filtret räknar därför hur ofta varje ord förekommer med liten bokstav i alla annonser.
- Filter 3: Står träffen där en kontaktperson brukar stå?

In [27]:
from collections import Counter

# Gör om träfflistan till en tabell
hits = pd.DataFrame(per_hits, columns=["id", "name", "pos", "context"])

# Filter 1: ser det ut som ett namn?
NAME_LIKE = re.compile(r"^[A-ZÅÄÖ][a-zåäö]+(?: [A-ZÅÄÖ][a-zåäö]+){0,2}$")
hits = hits[hits["name"].apply(lambda n: bool(NAME_LIKE.match(n)))]
print(len(hits), "träffar efter strukturfilter")

# Filter 2: används ordet som ett vanligt ord?
lower_counts = Counter()
for text in df_clean["description"]:
    lower_counts.update(re.findall(r"\b[a-zåäö]{2,}\b", text))

def is_common(name, min_count=20):
    return all(lower_counts[w.lower()] >= min_count for w in name.split())

hits["common_word"] = hits["name"].apply(is_common)

skills = json.load(open("../data/skills_2511.json", encoding="utf-8"))
skill_words = {s["skill"].lower() for s in skills}
hits["is_skill"] = hits["name"].str.lower().isin(skill_words)

# Filter 3: står träffen där en kontaktperson brukar stå?
cue = re.compile(r"kontakt|rekryter|frågor|ansvarig|hör av|ring |mejla|maila|fackliga",
                 re.IGNORECASE)
hits["near_cue"] = hits["context"].apply(lambda c: bool(cue.search(c)))
hits["late"] = hits["pos"] > 0.6

# Nivåer att läsa
tier1 = hits[hits["near_cue"] & hits["late"] & ~hits["is_skill"]]
tier2 = hits[~hits["common_word"] & ~hits["is_skill"] & ~hits.index.isin(tier1.index)]
print(len(tier1), "i nivå 1,", len(tier2), "i nivå 2")

9136 träffar efter strukturfilter
429 i nivå 1, 5755 i nivå 2

- 11 972 träffar → 9 136 efter strukturfiltret. En ganska liten del av träffarna såg inte ut som ett namn alls. Det är orden med små bokstäver, versaler (AB), siffror, skiljetecken och fler än tre ord.
- 429 i nivå 1 avser träffar som står nära en kontaktfras och sent i texten, och som inte är en känd kompetens. Det här är den mest sannolika platsen för riktiga namn.
- 5 755 i nivå 2 avser träffar som “inte är ett vanligt ord med liten bokstav” och fångar också produktnamn, bolag och titlar som alltid skrivs med stor bokstav (Azure-liknande ord, Scrum Master, Avaron), eftersom de aldrig förekommer i lowercase och därför inte räknas som vanliga ord. Nivån är alltså inte “troliga namn” utan “det som filtren inte kunde avfärda”.
- Resterande cirka 2 952 avser de träffar som filtret räknade som vanliga ord eller kompetenser och inte låg i nivå 1 och är nästan säkert falska.

### Plocka ut unika strängar

In [28]:
print(tier1["name"].nunique(), "unika strängar i nivå 1")
print(tier2["name"].nunique(), "unika strängar i nivå 2")

# Kollar nivå 1 efter personnamn: läs alla, grupperat
review1 = (tier1.groupby("name")
                .agg(annonser=("id", "nunique"), exempel=("context", "first"))
                .sort_values("annonser"))
print(review1.to_string())

# utskriften i output har tagits bort pga innehåller personnamn

169 unika strängar i nivå 1
1252 unika strängar i nivå 2
                               annonser                                                                                                        exempel
name
Advania                               1                        r rekryteringsprocessen i samarbete med Advania, tjänsten är en direktanställning hos A
Altova Mapforce                       1                het av mappningsverktyg, som exempelvis Altova Mapforce Erfarenhet av Java och Spring Boot Erfa
Administrator                         1                  ertifiering ServiceNow Certified System Administrator (CSA) ServiceNow Certified Implementati
Apache                                1                         t av Java och Spring Boot Erfarenhet av Apache Camel Erfarenhet av Kubernetes och Tanz
Ansvara                               1                        eda och stötta teamet i tekniska frågor Ansvara för systemarkitektur och tekniska vägva
Ants Tech Recruiters                  1           na rekrytering samarbetar Bankgirot med Ants Tech Recruiters. Urval sker löpande, så tveka inte att
Android                               1                         utveckling av native appar för iOS och Android samt Spring Boot, API:er och integratio
Andara Group                          1                   sort: Stockholm, hybridlösning möjlig   Andara Group ansvarar för hela rekryteringsprocessen
Azure Solutions                       1                nslösningar eller databashantering (ex. Azure Solutions Architect, TOGAF, Microsoft Data Engine
Azure Synapse                         1                  engineering inom Azure Data Factory och Azure Synapse. Erfarenhet av Azure Analysis Services
Blazor                                1                         igrering i komplexa miljöer. Kunskap om Blazor och Telerik Blazor. Erfarenhet av verkt
Bonus                                 1                          pension Förmåner via vår partner Benify Bonus vid tips av rekrytering Flexibla arbets
Awexia Executive Search               1        samarbetar vi med rekryteringsföretaget Awexia Executive Search och du ansöker här. Lägg märke till att
Azure Architect Expert                1         ktur och IAM • Certifiering inom TOGAF, Azure Architect Expert, AWS Solutions Architect eller motsvara
Azure Cloud                           1                    rande:     Erfarenhet av migrering till Azure Cloud   Erfarenhet av agil kravmetodik (t.ex.
Apache Kafka                          1                   ring. Certifiering inom Confluent eller Apache Kafka. Vi erbjuderFast anställning hos Avaron
Briljantin Consulting                 1          ormation om tjänsten, vänligen kontakta Briljantin Consulting. Vi accepterar inte ansökningar via e-p
Databricks                            1                     Engineering  Dokumenterad expertis inom Databricks, Apache Spark och utveckling av datapip
Databricks Workflows                  1           ta Factory för orkestrering (på väg mot Databricks Workflows) • Git och CI/CD pipelines för deployme
Data Management                       1                nterad erfarenhet inom: IT-arkitektur   Data Management   Informationsmodellering   Verksamhets
Danielsson                            1                     ngar om befattningen Kontakta Anna-Lena Danielsson på telefon [PHONE](växel). Din ansökan
Data Engineers                        1                  data lake-miljöer i nära samarbete med Data Engineers. Erfarenhet av versionshantering med Gi
Containers                            1                     kitektur (Oracle, AWS, GCP eller Azure) Containers och orkestrering (Docker, Kubernetes) I
Core Products                         1                  skap kring hur någon av Saabs nuvarande Core Products är uppbyggda. Ett nätverk inom verksamh
Computer Science                      1               nnefattar: MSc i Software Engineering / Computer Science eller motsvarande utbildningsbakgrund.
Cisco Catalyst                        1                 strukturen. Du bidrar i uppgradering av Cisco Catalyst Centre och säkerställer att lösningen s
Charlotta Fredhsdotter                1         älkommen att kontakta rekryterande chef Charlotta Fredhsdotter **** från och med 12 augusti. Då det är
Charlotta                             1                                           direkt via länken eller hör av dig till Charlotta på **** eller ****
Chaos Desktop                         1                   kunskaper/programvaror är ProjectWise, Chaos Desktop, Metadatahantering och filhanteringspro
Changers Hub                          1                    till fina initiativ som Women in Tech, Changers Hub, Pink Programming m.fl. Kontakt:  Vi se
Castra                                1                         I denna rekrytering samarbetar TePe med Castra. Ansökningar behandlas löpande, så tvek
Capgemini Engineering Academy         1  äddarsydda utvecklingsmöjligheter genom Capgemini Engineering Academy • Flexibla arbetsvillkor och konkurrens
Exchange Online                       1                 roll i en strategisk implementering av Exchange Online. 🔹 Utveckling – Möjlighet att arbeta i
Enerims                               1                         affärsområdesansvarig, som är medlem i Enerims ledningsgrupp och är baserad i Finland.
Enterprice Architect                  1           dulering av arkitektur i verktyg så som Enterprice Architect. Vårt arbetsspråk är svenska så du behö
Deloittes                             1                      öpande urval. Som ett kvalitativt led i Deloittes rekryteringsprocess genomgår våra slutk
Ekahau Sidekick                       1                i-optimering från Ekahau. Erfarenhet av Ekahau Sidekick i samband med mätning och analys. Merit
Elias Jakobson                        1                 ringsort: Sundbyberg Rekryterande chef: Elias Jakobson  Vänligen observera att rekryteringsarb
Eltel Networks                        1                 aljfrågor när det behövs. Om företaget  Eltel Networks Infranet AB Eltel är den ledande levera
Emma Hörnsten                         1                                                         nde. Ansvarig rekryterare på Incluso är Emma Hörnsten.
Expert                                1                         ner. Du ska inneha certifiering ITIL V3 Expert. Arbetslivserfarenhet av att ha tagit f
Data Science                          1                   ildning inom Computer Engineering eller Data Science/Datavetenskap. Erfarenhet från Customer
Mångfald                              1                       rändring för våra kunder. Jämställdhet, Mångfald och Inkludering Jämställdhet, mångfald
Motiveras                             1                      het och ett coachande förhållningssätt. Motiveras av att driva förändring och skapa struk
Natural Language Processing           1    eep learning-ramverk  • Kunskap om NLP (Natural Language Processing) • Kunskap inom versionshantering (t.ex
Placering Placering                   1             och innovationer tillsammans med oss   Placering Placering hos vår kund i Stockholm med möjlighet
Luleå Kommun                          1                   ting, men anställningen sker direkt hos Luleå Kommun. Vid eventuella frågor eller mer inform
Leda                                  1                           i Danderyd. Exempel på arbetsuppgifter: Leda och stötta teamet i tekniska frågor Ans
Kanban                                1                         renhet av agila arbetssätt t.ex. Scrum, Kanban, SAFe. • Certifiering inom IT-arkitektu
Kraftsystemet                         1                  hetens krav inom området Balansering av Kraftsystemet Minst 6 års erfarenhet av arbete i mynd
Johanna Norman                        1                 ll uppsägningstid Rekryteringsansvarig: Johanna Norman Lön: Fast månadslön Rekryteringen sker
Kronoberg                             1                      ablering i Växjö och utveckla affären i Kronoberg. Du behöver kunna kommunicera obehindra
Logic Apps                            1                     m Azure – särskilt kring integrationer, Logic Apps och molntjänster. • Erfarenhet av att a
Hemfrid                               1                        ail. I den här rekryteringen samarbetar Hemfrid med Gazella som partner. Rekrytering sk
Höör                                  1                           är att inom kommunerna Eslöv, Hörby och Höör hantera renhållningsfrågor med beaktand
Implementerat                         1                  hantering av dessa i komplexa miljöer - Implementerat, utvecklat och förvaltat IDP-plattforma
Gurobi                                1                         ogrammering och optimering. T.ex CPLEX, Gurobi, eller GAMS. • Kännedom om energisystem
Gästrike Vatten                       1                 ansökan. Inför rekryteringsarbetet har Gästrike Vatten tagit ställning till rekryteringskanale
Helm                                  1                           od och automatisering (t.ex. Terraform, Helm). Önskad profil Du är både strateg och
Gazella                               1                        är rekryteringen samarbetar Hemfrid med Gazella som partner. Rekrytering sker i samarbe
Google Cloud                          1                   ammering · Cloud-lösningar (Azure, AWS, Google Cloud) · IT-säkerhet och infrastruktur · Proj
Fatima Bekori                         1                  änligen kontakta ansvarig rekryterare:  Fatima Bekori via **** du frågor angående registrerin
Farshad Akondi                        1                 ockholm, Sundbyberg  Rekryterande chef: Farshad Akondi Vi kan komma att påbörja urvalet under
Extrahera                             1                      ra API-anrop för effektiv datahantering Extrahera och återskapa affärsregler från befintl
Polismyndighetens                     1              ppdraget ingår kompetensöverföring till Polismyndighetens egen personal och dokumentation av geno
Podman                                1                         ar, exempelvis Docker, Kubernetes eller Podman • Utbildning, certifiering eller erfare
Quadruped Rekrytering                 1          enna rekrytering samarbetar Yaskawa med Quadruped Rekrytering. Hör av dig med frågor eller skicka din
Platform Engineering                  1           t av OpenShift Erfarenhet av DevOps och Platform Engineering Erfarenhet av Linux Erfarenhet av säker
Pink Programming                      1               tiativ som Women in Tech, Changers Hub, Pink Programming m.fl. Kontakt:  Vi ser fram emot att hö
Peops Relations                       1                med vår upphandlade rekryteringspartner Peops Relations, som hanterar delar av processen. Vi un
Mälarenergi                           1                    ör mer information kring rekrytering på Mälarenergi. Mälarenergi utgör en vital del av samh
Mulesoft Anypoint                     1                - Erfarenhet och/eller certifiering i Mulesoft Anypoint Platform, WSO2 eller annan ledande inte
Microsoftprodukter                    1             ed AD, Entra ID och Azure. Migrering av Microsoftprodukter från OnPrem till Online Att praktiskt t
Miltton                               1                         CV. Rekryteringen sker i samarbete med Miltton, som Svenska Röda Korset har ett samarb
Modern Requirements                   1            v informationsmodellering • arbetat med Modern Requirements  Kraven ska framgå tydligt i CV och mar
Microsoft Windows                     1          ing, kunskap och erfarenhet inom:   \t•  Microsoft Windows och M365  \t• Ärendehantering \t• ITIL \t•
Marketing Automation                  1           ur och modellering kopplat till CRM och Marketing Automation (MA). Övrig info Startdatum: 2026-08-31
Microsoft Enterprise                  1           senaste 10 åren av komplexa och moderna Microsoft Enterprise miljöer. • Arbetat med säkerhetsfrågor
Microsoft Solutions Partner           1     Azure och Fabric) samt hybrid/on-prem. Microsoft Solutions Partner for Data & AI (Azure) (certifiering på
Lumera                                1                         ft MeriterandeKunskap och erfarenhet av Lumera Erfarenhet av migrering till Lumera För
Swedavia                              1                       llnad – läs mer här! Jobba hos oss | Om Swedavia  För en objektiv och rättvis rekryterin
Teamtailor                            1                                                             in den här via vårt rekryteringssystem Teamtailor.
Team Lead                             1                      tering och agilt arbete. Erfarenhet som Team Lead i agila team enligt Scrum. God förståel
Talent Acquisition Partner            1     k placering. Vänligen kontakta ansvarig Talent Acquisition Partner för mer information. Redo att göra skil
Snowflake                             1                      ndaoptimering   Erfarenhet av Redshift, Snowflake, BigQuery eller liknande datalager   Er
Skellefteå Kraft                      1               routing och switching   Vilka är vi då? Skellefteå Kraft möjliggör samhällets elektrifiering och
Skapa                                 1                          lera och forma vårt lokala erbjudande ✅ Skapa och utveckla kundrelationer ✅ Rekrytera
Software Engineering                  1           a kraven för tjänsten innefattar: MSc i Software Engineering / Computer Science eller motsvarande ut
Sigma                                 1                                    du mer än välkommen att kontakta oss på Sigma! 😊 Välkommen med din ansökan!
Shopify                               1                        ktutveckling  Mycket god förståelse för Shopify och sajtoptimering  Vana att jobba data
Server Subscription Edition           1    arePoint 2016. Erfarenhet av SharePoint Server Subscription Edition. Erfarenhet av konfigurering av on-prem
Service Manager                       1                ering och scripting (t.ex. PowerShell), Service Manager och BizTalk. Det är även meriterande om
Semantic Kernel                       1                & orkestrering som LangChain/LangGraph, Semantic Kernel eller motsvarande. RAG & sök: VektorDB,
Scriptprogrammering                   1            utveckla ditt svar Har du erfarenhet av Scriptprogrammering i Powershell? Vänligen utveckla ditt sv
Region Kronoberg                      1               DPR). Kontakta ansvarig rekryterare hos Region Kronoberg vid skyddad identitet för vidare inform
Redshift                              1                       för prestandaoptimering   Erfarenhet av Redshift, Snowflake, BigQuery eller liknande dat
Varbi                                 1                           ansökningar via vårt rekryterinssystem Varbi. Partille kommun tar inte emot några pe
Västra Götalandsregionen              1       platsen. Läs mer om vår verksamhet här: Västra Götalandsregionen - Informatik och Standardisering  Rekry
Windows Server                        1                 ll för managering och automatisering av Windows Server Gedigen erfarenhet av säkerhetsarbete o
Zero Trust                            1                     sarkitektur, identitetshantering (IAM), Zero Trust eller liknande säkerhetsmodeller samt a
Techster Solutions                    1             antering      Ansökan Tror du att du är Techster Solutions nästa stjärna? Tveka då inte att skicka
Telge                                 1                          r om några av våra medarbetare som valt Telge: Vi valde Telge  Mångfald inkludering o
Tidsperiod                            1                     isation Kontaktperson (namn och e-post) Tidsperiod (månad/år – månad/år) Kort beskrivning
Trelleborgs                           1                    lsarbete. Inför rekryteringsarbetet har Trelleborgs kommun noggrant tagit ställning till re
Jira                                  2                           ch säkerställer spårbar kravhantering i Jira/Confluence. En central del är att minim
Luleå Energi                          2                   att tillgångar och information skyddas. Luleå Energi har valt kanaler för denna rekrytering
Magnus Åkerling                       2                eringsort: Stockholm Rekryterande chef: Magnus Åkerling  Vi vill göra dig uppmärksam på att bak
Oracle                                2                          5 års erfarenhet av Java, Spring Boot, Oracle och Weblogic Minst 5 års erfarenhet av
Word                                  2                           änligen svara på frågorna i ett separat Word dokument • Referensuppdrag Övrig inform
Valora Bemanning                      2               renhet inom rollen. Om Valora Bemanning Valora Bemanning är ett bemannings- och rekryteringsföre
Referensperson                        2                 . Konsultens namn och kontaktuppgifter. Referensperson (namn, e-post, telefonnummer). Informat
Team Effektiv                         2                  tjänsten kontakta gärna **** på **** Om Team Effektiv Effektiv är det innovativa och personli
Brillante                             2                      är att rekryteringsprocessen sker genom Brillante och du anställs direkt hos Unionen. Vi
Arbetsprov                            2                     /jobba-hos-oss/var-rekryteringsprocess/ Arbetsprov kan komma att tillämpas. Välkommen med
Architects                            2                     m du har:  • Certifiering inom SAFe for Architects. • Relevanta kurser eller certifieringa
Asap                                  2                           iod: Tillsvidare   Sista ansökningsdag: Asap Sway Sourcing är en innovativ rekryteri
Ansible                               2                        e DevOps och automatisering (Terraform, Ansible, GitOps) Containerlösningar (Docker, Ku
Active Search                         2                  a rekrytering samarbetar Åre kommun med Active Search. Med över 15 års erfarenhet har vi bygg
Policy                                2                          Governance och livscykelhantering  *   Policy enforcement och policy decision (PBAC,
Precio Fishbone                       2                ektrekrytering och du blir anställd hos Precio Fishbone. Professionals Nord sköter rekryterings
Red Hat                               2                        oud), containerteknologier (Kubernetes, Red Hat OpenShift) och mikroservices (Spring Bo
Ramboll                               2                        ållbar förändring med Ramboll i Sverige Ramboll grundades i Danmark och är en stiftelse
Qlik Sense                            2                     ete kring ETL mot BI-plattformar, gärna Qlik Sense. Start/Längd Start: Enligt överenskomme
Identity Governance                   2            ity  *   Access Management och PAM  *   Identity Governance och livscykelhantering  *   Policy enfo
Danda                                 2                          fiering inom SAP Erfarenhet som konsult Danda erbjuder: Spännande uppdrag hos både sv
Computer Sweden Recruitment           2     denna rekrytering samarbetar Tutus med Computer Sweden Recruitment. Välkommen in med din ansökan! Om Tutus
Enterprise Architect                  2           llering och processvisualisering (t.ex. Enterprise Architect) Erfarenhet av att definiera och ta fra
Addilon                               2                        ch godkännas i en säkerhetsprövning. Om Addilon Rekrytering och uthyrning av rätt chefe
Sokigo                                2                         ar löpande. I den här rekryteringen har Sokigo redan gjort våra val av annonskanaler o
Jenkins                               3                        D-pipelines (t.ex. GitHub Actions eller Jenkins). Nyfikenhet kring övervakning och logg
Manager                               3                         märk mejlet med ”Erfaren Configuration Manager med fokus på teknisk kravhantering (130

Personnamn går nu att identifiera i nivå 1-listan med unika strängar. Dessa kommer att behöva maskeras, även utskriften av review1 har tagits bort inför commit till Git.

In [29]:
# Kollar nivå 2 efter personnamn: läs alla, grupperat
# utskriften i output tagits bort pga kan innehålla personnamn
review2 = (tier2.groupby("name")
                .agg(annonser=("id", "nunique"), exempel=("context", "first"))
                .sort_values("annonser"))
print(review2.to_string())

                                       annonser                                                                                                                exempel
name
Workday Integration Framework                 1          ompetenskrav Dokumenterad erfarenhet av Workday Integration Framework Workday inbound och outbound-integratio
About Rasulson Consulting                     1              vå av relevant erfarenhet (antal år)    About Rasulson Consulting Rasulson Consulting is a specialized st
About Epical                                  1                           Sverige och ha giltigt arbetstillstånd. About Epical  Epical is a Nordic data consultancy dr
Zeek                                          1                                   ätverkstrafik t.ex. Wireshark, T-Shark, Zeek · Förståelse för internetkommunikation
Zeppelin                                      1                               egmentet för motorer och generatorer är Zeppelin en ledande leverantör av lösningar för
Yaskawa Motoman                               1                        stems Architect Automation Engineering. Yaskawa Motoman är en japansk global ledare inom automa
Yaskawa Electric Corporation                  1           es på 70-talet och är en del av globala Yaskawa Electric Corporation, en koncern börsnoterad i Tokyo. Yaskaw
Workspace                                     1                              pplat till Incident Införa och rulla ut Workspace till olika användargrupper Förbereda fö
Workshopfacilitering                          1                    inom pension och livförsäkringsområdet Workshopfacilitering Van att leda arbete såsom krav och utre
Workshop Suite                                1                         h integrerad i diagnostikverktyget SWS (Workshop Suite). Du blir en viktig del i kedjan mellan
Workplace Specialist                          1                   möjlighet att axla en nyckelroll som IT Workplace Specialist och forma, bygga och säkra morgondagens
Workplace Operations                          1                   expertis med kundnära arbete? Vårt team Workplace Operations söker nu en senior konsult som trivs i
Adecco                                        1                                  konsultuppdrag där du blir anställd av Adecco och arbetar på uppdrag hos Øresundsbron
Addovations                                   1                            Hos oss finns det möjlighet att påverka Addovations framtid och växa med bolaget. Dessutom
Active Workspace                              1                       iljöer, särskilt system som Teamcenter, Active Workspace eller Catia  Rollen är tänkt som ett he
Acquirer                                      1                               nom hela betalcykeln, som ex. Merchant, Acquirer, Issuer, Card schemes och Open Banking.
Waterfall                                     1                              att arbeta med portföljprocesser i både Waterfall och Agile-miljöer. God förståelse för f
Aars                                          1                                   rn, ägd av det norska investmentbolaget Aars, med cirka 1500 anställda – varav 500 i
Windowsservergrupp                            1                     ist kommer du att tillhöra myndighetens Windowsservergrupp. Ditt huvudfokus blir att stötta och fö
Windowsserver                                 1                          tning, drift och utvecklig inom området Windowsserver med fokus på Hyper-V, för att vi skall
Agent Workspace                               1                         Service Operations Workspace och/eller Agent Workspace Kunskap om Now Assist, Virtual Agent el
Affärsområdeschef Digital                     1              ingsort: Karlshamn  * Rapporterar till: Affärsområdeschef Digital Infrastruktur  * Start: Enligt överensk
Affärsgemensamt                               1                        porterar till chef IT inom Koncern- och Affärsgemensamt. Vi erbjuder en hybrid arbetsmodell vil
Adven Sveriges                                1                         etet med att utveckla vår IT-miljö. Som Adven Sveriges infrastrukturexpert ansvarar du för att
Advant                                        1                                 Erfarenhet av äldre ABB familjer så som Advant system, Sattline mm. Erfarenhet/certifi
Adobe Experience Manager                      1               ösningsarkitekt med djup kompetens inom Adobe Experience Manager, som vill bidra till utvecklingen av hå
Adobe Experience                              1                       a system? Har du dessutom erfarenhet av Adobe Experience Platform och Adobe Customer Journey Ana
Adobe Creative Suite                          1                   otyper och visuella koncept i Figma och Adobe Creative Suite Säkerställa tillgänglighet enligt WCAG
Admino                                        1                                 Ora och vår nya webbaserade systemserie Admino. Vi befinner oss i en omfattande övergå
Access Review                                 1                          m IAM-koncept som JEA, JIT, RBAC, ABAC  Access Review. •    Erfarenhet av federerad SSO med S
Access Manager                                1                         ffentlig sektor. Erfarenhet av OpenText Access Manager samt OpenText Identity manager. Kunskap
Workflows                                     1                              a Sharepoint versioner • Kunskap om hur Workflows inom Sharepoint fungerar • God förmåga
Vinnova                                       1                                 projekt med extern finansiering (t.ex. Vinnova, EU, Tillväxtverket). • Skapa förutsätt
Vendor Manager                                1                         lning. Du arbetar nära Service Manager, Vendor Manager, arkitekter och säkerhetsfunktioner och
Anläggningsinformationsstöd                   1            Som lösningsarkitekt tillhör du enheten Anläggningsinformationsstöd, som ansvarar för systemförvaltning och
Anders                                        1                                 g, frihet och samarbete står i fokus. 💡 Anders, en av våra kollegor som gick från ekon
Analytiker Bedrägeri                          1                             Vi söker för kunds räkning en Analytiker Bedrägeri. Uppdragsbeskrivning  Sektionen Bedräge
Analysstödsystem                              1                       rbetsbeskrivning Vår uppgift på gruppen Analysstödsystem är att ta ett helhetsansvar för nyutvec
Amplitude                                     1                              et av verktyg som dbt, Airflow/Dagster, Amplitude eller Looker  • Uppbyggnad av Data Coun
Amdocs                                        1                                  och engelska. MeriterandeErfarenhet av Amdocs. Erfarenhet av TM Forum. Vi erbjuderFas
Amazons                                       1                                rtifieringar inom andra molnmiljöer ex. Amazons och Googles • Erfarenhet från organisat
Altova Mapforce                               1                        sk användning av mappningsverktyg såsom Altova Mapforce. Arbete med REST- och SOAP-baserade API
Altova                                        1                                 terAnvändning av mappningsverktyg såsom Altova Mapforce för datakonvertering och trans
Alteryx                                       1                                ade rapporteringsmiljöer. Erfarenhet av Alteryx eller liknande legacy ETL-verktyg. Erfa
Almega                                        1                                 Friskvårdsbidrag och kollektivavtal med Almega  ECIT är ett företag med nordiska rötte
Windowsanvändare                              1                       v att bygga självbetjäningsportaler för Windowsanvändare, baserat på SCCM och molnbaserade verkt
Windows Powershell                            1                      backup/restore m.m   Goda kunskaper om Windows Powershell och/eller andra scriptspråk    Meritera
Workato                                       1                                renhet av automationsplattformar (t.ex. Workato, UiPath eller likvärdigt) Erfarenhet av
Architecture Definition                       1                h underhålla arkitekturleverabler såsom Architecture Definition Documents (ADD enligt TOGAF) och Soluti
Architect Manager                             1                      ise Architect, Lead Solution Architect, Architect Manager eller liknande  Ansökan och nästa steg
Apply                                         1                                  icka in din ansökan genom att klicka på Apply now senast den 2025-02-28. Vi tar inte
Applikationsspecialist                        1                 ollegor, BI-arkitekter, RPA utvecklare, Applikationsspecialist och Verksamhetsutvecklare. I denna tjän
Apache Tomcat                                 1                          ava Topology Suite (JTS). Erfarenhet av Apache Tomcat. Erfarenhet av integrationsdesign. Vi e
Apache Spark Notebooks                        1                 rs arbetslivserfarenhet av utveckling i Apache Spark Notebooks. Minst tre (3) års arbetslivserfarenhet
Apache Iceberg                                1                         udera arbete med Databricks/Delta Lake, Apache Iceberg, Hadoop/Hortonworks, Snowflake, Google
Apache Hudi                                   1                            ed teknologier som Iceberg, Delta Lake, Apache Hudi, och Kafka för att hantera både batch-
Anställningsperiod                            1                     om inleds med eventuell provanställning Anställningsperiod/tillträde: Enligt överenskommelse Omfat
Ansible Terraform                             1                      iserings- och managerings-plattformarna Ansible Terraform, Saltstack och/eller Puppet. Som konsul
Vitec Software Group                          1                   a produkter på www.samfundssystem.se Om Vitec Software Group Vitec är ledande inom Vertical Market S
Visual Analytics                              1                       s erfarenhet av visualisering i SAS VA (Visual Analytics). Du har minst tre års erfarenhet av pr
Visma Spcs                                    1                             att jobba projektdrivet? Perfekt! Vi på Visma Spcs söker just nu flera Business Analysts t
Visma Software Nordic                         1                   datahantering och maximal affärsnytta. Visma Software Nordic befinner sig i en spännande fas i vår u
Visma Recruit                                 1                          iskt ansökningsformulär i samarbete med Visma Recruit. Vid ansökan kommer dina personuppgifte
Virtualiseringstekniker                       1                 tjänster i moln samt egen serverdrift. Virtualiseringstekniker för servrar och system samt automatiser
Automationsresa                               1                                 Vill du vara med och forma vår Automationsresa? Würth koncernen etablerar ett nytt fra
Aure                                          1                                   ockups baserat på krav. Kommer arbeta i Aure devops och andra lämpliga systemstöd fö
Attendos                                      1                               a och säkerställa robusta lösningar för Attendos applikationslandskap, dataflöden och in
Atlassian Confluence                          1                      F5 BigIP  ·     MS Sharepoint  ·     Atlassian Confluence & Jira  ·     Azure  ·     Entra ID  ·
Atlan                                         1                                  -DMBOK Erfarenhet av Collibra, Purview, Atlan eller liknande TOGAF / ArchiMate MDM Er
Veeva                                         1                                   arkitekturen bakom både Salesforce och Veeva? Då har vi det perfekta deltidsuppdrage
Utvecklingsingenjör                           1                    ch innovation. Din uppgift I rollen som Utvecklingsingenjör spelar du en nyckelroll i att förverkli
Unified Data Platform                         1                   av analyslösningar till den gemensamma Unified Data Platform. Agera mentor och förebild för arkitekt
Unified Commerce                              1                       butikslogistik, varuflöden eller Retail/Unified Commerce Erfarenhet från verksamheter med regula
Tydliggör                                     1                              ar med våra tjänster för stora företag. Tydliggör i din ansökan vilken inriktning du har.
Tunnelbana                                    1                                             Kravledare till sektion Tunnelbana – investeringsprojekt inom framtida tra
Atea                                          1                                   fil Vill du växa tillsammans med oss på Atea? Brinner du för att skapa smarta, trygg
Assist                                        1                                  with business goals within your scope. Assist in developing business cases to support
Artemis                                       1                                av  Minst 3 års arbetslivserfarenhet av Artemis Minst 3 års arbetslivserfarenhet av OAu
Arla                                          1                                   ftningen hjälper vi företag som Holmen, Arla, Carlsberg och Scania att effektivisera
Arkitekturkontor                              1                       g. Du kommer ingå i enheten Projekt och Arkitekturkontor. Om rollen Som vår nästa Lösningsarkite
Avro                                          1                                   emutveckling inom ett masterdata-område Avro Json React Databaser (SQL) REST Version
Avokis                                        1                                 ll kunder och interna team med fokus på Avokis tjänster, AI samt Microsoft 365-lösning
Avoki                                         1                                  an du klicka dig vidare till annonsen:  Avoki är ett framstående konsultbolag med fok
Aveva                                         1                                  rface design, gärna med plattformar som Aveva, Micro SCADA eller liknande - Har erfar
Aveers                                        1                                                     ning: 100% Ansök idag och bli en del av Aveers växande teknikteam.
Polars                                        1                                 taanalys, t.ex. Python och Pandas eller Polars Skriver, förstår och kommunicerar obehi
Platina                                       1                                erade på standardprodukter som M-Files, Platina eller W3D3, samt viss programmering och
Platform Success Engineer                     1              ch driva Sveriges energiomställning som Platform Success Engineer – OpenShift  Svenska kraftnät är en av
Personio                                      1                               annat Google for Education, Schoolsoft, Personio och Fortnox), du leder samarbetet med l
Personbeskattning                             1                      m jobbet Som systemarkitekt inom område Personbeskattning är du en nyckelperson när målarkitektur
Performance Management                        1                 m vill bli Business Analyst i vårt team Performance Management. Är du den vi söker? Nu söker vi en inn
Performance                                   1                            om konsult inom Enterprise Technology & Performance tror vi att ett gediget intresse för ek
Pegas                                         1                                  vecklare och säkerställa efterlevnad av Pegas bästa praxis och kodstandarder. Driva e
Pega Lead                                     1                              l du bli en av oss? Vi söker en erfaren Pega Lead System Architect (LSA) till vårt Center
Pega Certified Senior                         1                  samhetskritiska system. Certifieringar: Pega Certified Senior System Architect (PCSSA). Pega Certifie
Parts Structures                              1                       aster Data, Maintenance Plans och Spare Parts Structures. Du stöttar arbete med datarensning, mi
Azure Pipelines                               1                        m GitHub Actions, GitLab CI, Circle CI, Azure Pipelines. * Arbeta med containerisering och orke
Azure Networking                              1                        Azure-ekosystemet, t.ex. Azure DevOps, Azure Networking, och Azure Storage bedöms det som merit
Azure Machine Learning                        1                 h modellförvaltning. Azure AI Services, Azure Machine Learning eller liknande plattformar. Vem är du?
Azure Local                                   1                            zure) är navet och edge-plattformar som Azure Local / Azure Arc och AWS Outposts utgör en n
Azure Integrations Services                   1            djupgående erfarenhet och förståelse av Azure Integrations Services (Logic Apps, Service Bus, API Managemen
Azure Fundamentals                            1                     de). Certifiering: Microsoft Certified: Azure Fundamentals och Microsoft Azure Administrator Assoc
Azure Fridays                                 1                          för Azure. I teamet har vi standups och Azure Fridays, där vi är uppkopplade i teamet, jobbar
Azure Fabric                                  1                            och plattformar som dbt, Snowflake och Azure Fabric • Goda kunskaper i Svenska och Engelska
Azure Event Hub                               1                        nklusive Databricks, Synapse Analytics, Azure Event Hub och Delta Lake. Färdigheter i datamodel
Azure Developer Associate                     1              s Architect Expert Microsoft Certified: Azure Developer Associate Erfarenhet av hybridintegrationer mella
Azure Data Lake                               1                        zure Synapse, Databricks, Data Factory, Azure Data Lake, Microsoft Fabric &Data Vault  Hands-on
Azure Certified Solutions                     1              L • SAFe (Scaled Agile Framework) • AWS/Azure Certified Solutions Architect • CISSP eller CISM. Som perso
Azure Bicep                                   1                            nfrastructure as Code” med tekniker som Azure Bicep och Terraform. Byggverktyg som Azure De
Azure Analysis                                1                         actory och Azure Synapse. Erfarenhet av Azure Analysis Services och Python för databehandling
Azure Administrator Associate                 1          tifieringar inom:  Microsoft Certified: Azure Administrator Associate Microsoft Certified: Azure Solutions Ar
Axway Amplify                                 1                          Kafka) BizTalk Sterling File Integrator Axway Amplify API Management  Ansökan Välkommen att s
Operations Bridge                             1                      nings söker vi en lösningsarkitekt inom Operations Bridge Manager (OBM). I rollen som lösningsark
Team Foundation Server                        1                 ntlig sektor. Minst 2 års erfarenhet av Team Foundation Server / ADS. Minst 1 års erfarenhet av system
Behind                                        1                                 öftet är att alltid vara ”Beside you”, ”Behind you” och ”Before you”. Vi kallar det fö
Behavior Driven Development                   1            Q och JBOSS. Dokumenterad erfarenhet av Behavior Driven Development (BDD). Dokumenterad erfarenhet av GitOp
Bastard Burgers                               1                         framtidens digitala gästupplevelse hos Bastard Burgers? Vi söker en Teknisk Produktägare till
Bankgirothär                                  1                           ringar? Läs om flerlediga tjänster från Bankgirothär. Vi ser fram emot din ansökan! Om Bankg

Inga personnamn identifieras i nivå 2-listan, därför behövs ingen maskering göras.

In [30]:
# skriver om review1 till vanlig kolumn med radnummer
# utskriften i output har tagits bort pga innehåller personnamn
review1 = review1.reset_index()                    
print(review1[["name", "annonser"]].to_string())

                              name  annonser
0                          Advania         1
1                  Altova Mapforce         1
2                    Administrator         1
3                           Apache         1
4                          Ansvara         1
5             Ants Tech Recruiters         1
6                          Android         1
7                     Andara Group         1
8                  Azure Solutions         1
9                    Azure Synapse         1
10                          Blazor         1
11                           Bonus         1
12         Awexia Executive Search         1
13          Azure Architect Expert         1
14                     Azure Cloud         1
15                    Apache Kafka         1
16           Briljantin Consulting         1
17                      Databricks         1
18            Databricks Workflows         1
19                 Data Management         1
20                      Danielsson         1
21                  Data Engineers         1
22                      Containers         1
23                   Core Products         1
24                Computer Science         1
25                  Cisco Catalyst         1
26          Charlotta Fredhsdotter         1
27                       Charlotta         1
28                   Chaos Desktop         1
29                    Changers Hub         1
30                          Castra         1
31   Capgemini Engineering Academy         1
32                 Exchange Online         1
33                         Enerims         1
34            Enterprice Architect         1
35                       Deloittes         1
36                 Ekahau Sidekick         1
37                  Elias Jakobson         1
38                  Eltel Networks         1
39                   Emma Hörnsten         1
40                          Expert         1
41                    Data Science         1
42                        Mångfald         1
43                       Motiveras         1
44     Natural Language Processing         1
45             Placering Placering         1
46                    Luleå Kommun         1
47                            Leda         1
48                          Kanban         1
49                   Kraftsystemet         1
50                  Johanna Norman         1
51                       Kronoberg         1
52                      Logic Apps         1
53                         Hemfrid         1
54                            Höör         1
55                   Implementerat         1
56                          Gurobi         1
57                 Gästrike Vatten         1
58                            Helm         1
59                         Gazella         1
60                    Google Cloud         1
61                   Fatima Bekori         1
62                  Farshad Akondi         1
63                       Extrahera         1
64               Polismyndighetens         1
65                          Podman         1
66           Quadruped Rekrytering         1
67            Platform Engineering         1
68                Pink Programming         1
69                 Peops Relations         1
70                     Mälarenergi         1
71               Mulesoft Anypoint         1
72              Microsoftprodukter         1
73                         Miltton         1
74             Modern Requirements         1
75               Microsoft Windows         1
76            Marketing Automation         1
77            Microsoft Enterprise         1
78     Microsoft Solutions Partner         1
79                          Lumera         1
80                        Swedavia         1
81                      Teamtailor         1
82                       Team Lead         1
83      Talent Acquisition Partner         1
84                       Snowflake         1
85                Skellefteå Kraft         1
86                           Skapa         1
87            Software Engineering         1
88                           Sigma         1
89                         Shopify         1
90     Server Subscription Edition         1
91                 Service Manager         1
92                 Semantic Kernel         1
93             Scriptprogrammering         1
94                Region Kronoberg         1
95                        Redshift         1
96                           Varbi         1
97        Västra Götalandsregionen         1
98                  Windows Server         1
99                      Zero Trust         1
100             Techster Solutions         1
101                          Telge         1
102                     Tidsperiod         1
103                    Trelleborgs         1
104                           Jira         2
105                   Luleå Energi         2
106                Magnus Åkerling         2
107                         Oracle         2
108                           Word         2
109               Valora Bemanning         2
110                 Referensperson         2
111                  Team Effektiv         2
112                      Brillante         2
113                     Arbetsprov         2
114                     Architects         2
115                           Asap         2
116                        Ansible         2
117                  Active Search         2
118                         Policy         2
119                Precio Fishbone         2
120                        Red Hat         2
121                        Ramboll         2
122                     Qlik Sense         2
123            Identity Governance         2
124                          Danda         2
125    Computer Sweden Recruitment         2
126           Enterprise Architect         2
127                        Addilon         2
128                         Sokigo         2
129                        Jenkins         3
130                        Manager         3
131                     Powershell         3
132                       Weblogic         3
133                       Building         3
134                          Azure         3
135                        Balders         3
136        Enterprise Architecture         3
137         Tillsvidareanställning         3
138                          Tutus         3
139                     Tetra Core         3
140                  Kafka Connect         4
141                    Unik Resurs         4
142                         Spring         4
143     Ljung Kompetensförsörjning         4
144                     Confluence         4
145                        Actions         5
146                       Effektiv         5
147                  Sway Sourcing         5
148                            Van         5
149                 Futuria People         5
150                         Python         5
151                     Prometheus         5
152                   Helsingborgs         5
153                         Adecco         5
154                           Java         6
155                   Aamir Faried         6
156                         Sökord         6
157     Sparx Enterprise Architect         7
158                     Erfarenhet         8
159              Läkemedelsverkets         8
160                     Kubernetes         8
161                       Linkedin         8
162                    Spring Boot         8
163                        Förmåga         9
164                         Fidler         9
165                  Visma Recruit        12
166                     Intervjuer        13
167                       Anpassar        18
168                          Ansök        25

### Maskera hittade personnamn i nivå 2

In [31]:
# radnummer för manuellt identifierade personnamn
real_idx = [20, 26, 27, 37, 39, 50, 61, 106, 155]                # radnumren med personnam
real_names = review1.loc[real_idx, "name"].tolist()
print(len(real_names), "riktiga personnamn")

9 riktiga personnamn

In [32]:
# maskera längst först, så att "Förnamn Efternamn" byts ut före "Förnamn"
names_sorted = sorted(real_names, key=len, reverse=True)
pattern = re.compile(r"\b(?:" + "|".join(re.escape(n) for n in names_sorted) + r")\b")

df_clean["description"] = df_clean["description"].apply(lambda t: pattern.sub("[NAMN]", t))

In [33]:
# kontrollera att maskeringen fungerade
remaining = df_clean["description"].apply(lambda t: bool(pattern.search(t))).sum()
print(remaining, "annonser innehåller fortfarande ett valt namn")   # ska vara 0

masked = df_clean["description"].str.count(r"\[NAMN\]").sum()
print(masked, "namn maskerade i", (df_clean["description"].str.contains(r"\[NAMN\]")).sum(), "annonser")

0 annonser innehåller fortfarande ett valt namn
16 namn maskerade i 16 annonser

### Spara städad df till json

In [34]:
out_path = Path("..") / "data" / "ads_clean.json"
out_path.parent.mkdir(exist_ok=True)                # skapar mappen om den saknas, annars händer inget

df_clean.to_json(out_path, orient="records", force_ascii=False, indent=2)
print("Sparade", len(df_clean), "annonser till", out_path.resolve())

Sparade 4266 annonser till /home/irene/Desktop/10 Projekt i Data Science/End-to-end-projekt-i-Data-Science/data/ads_clean.json