# Baseline
Den övergripande explorativa dataanalysen genomförs separat i projektets EDA 01_exploration. Den här notebooken fokuserar på att bygga och testa projektets baseline för kompetensidentifiering.

Baselinen utvecklas endast på träningsdata. Projektets test-set används
senare för slutlig utvärdering.

In [27]:
# läser in träningsannonser:
import json
import pandas as pd
import re

with open("../data/train_set.json", "r", encoding="utf-8") as file:
    ads = json.load(file)

df = pd.DataFrame(ads)

In [28]:
# liten EDA som är relevant för baseline:
df[["id", "title", "published", "region", "description"]].head()

,id,title,published,region,description
0,29556320,Business Consultant Dynamics 365 Supply Chain ...,2025-03-19T10:04:43,Stockholms län,Har du erfarenhet av Dynamics 365 och/eller AX...
1,31266797,Hälsoinformatiker för framtidens vårdinformation,2026-07-10T17:08:31,Östergötlands län,"Omvärlden förändras i snabb takt. Ny teknik, n..."
2,31129893,Data Scientist till Innovativt Bolag,2026-06-02T19:12:40,Västra Götalands län,Är du en analytisk och lösningsorienterad pers...
3,29479271,Dynamics 365 Finance Consultant,2025-02-19T12:38:38,NaN,Vill du arbeta med den senaste tekniken och hj...
4,31249545,"Enterprise arkitekt, Gävle/Uppsala/Stockholm",2026-07-06T01:35:55,Gävleborgs län,Lantmäteriet är den myndighet som kartlägger S...

In [29]:
# Enkel kontroll av datan, dubbelkollar saknade värden:
df["description"].isna().sum()

np.int64(0)

In [30]:
# dubbelkollar id-dubbletter:
df["id"].duplicated().sum()

np.int64(0)

In [31]:
# läser in kompetenserna för SSYK 2511
with open("../data/skills_2511.json", "r", encoding="utf-8") as file:
    skills_data = json.load(file)

In [32]:
# kontrolerar hur filen ser ut:
print("\nStruktur:",type(skills_data))
print("----------------------------")
skills_data[0]

Struktur: <class 'list'>
----------------------------

{'skill_id': '13ad_dCC_Tn6',
 'skill': 'OOS, styr- och utvecklingsmodell',
 'headlines': ['Styr- och utvecklingsmodeller']}

In [33]:
# bygger en lista med kompetensnamn som baseline kan matcha mot:
skill_names = [
    item["skill"]
    for item in skills_data
]

print("\nAntal kompetenser:", len(skill_names))
print("----------------------------")

print("\nExempel på 20 kompetenser:")
skills_df = pd.DataFrame(skills_data)
print(skills_df.head(20))
print("----------------------------")

Antal kompetenser: 204
----------------------------

Exempel på 20 kompetenser:
        skill_id                                              skill  \
0   13ad_dCC_Tn6                   OOS, styr- och utvecklingsmodell
1   16ZN_3Zp_bYV                                Odoo, molnplattform
2   19PK_uxU_Wzy                              Bower, pakethanterare
3   1CmG_8hR_igc                                   Bluetooth-teknik
4   1QYQ_Xka_TQ5      Microsoft Autopilot, systemutvecklingsverktyg
5   2CXh_FUJ_vTH  Office SharePoint Server (MOSS), applikationsp...
6   2rqG_WLp_em4                   Ledningssystem (ISO 9000-serien)
7   2vCi_hQz_Y9o                                         WAP-teknik
8   39C3_4Tm_3ud                       Asset Information Management
9   3H7m_pt8_7b2                HTTP/HTTPS, kommunikationsprotokoll
10  3JPR_oR7_UUS      Sun Java Enterprise System, webbserverprogram
11  3KME_Qwm_D4V                                IBM Integration Bus
12  3nRt_vck_Jrv                        Elixir, programmeringsspråk
13  44NU_bjv_f3M           OOAD, objektorienterad analys och design
14  49fH_K3e_Fbm               AZ-900: Microsoft Azure Fundamentals
15  4Dqo_LPf_qrU          Web Content Accessibility Guidelines/WCAG
16  4f1v_w91_qVM                                  Systemförvaltning
17  4ob7_R6h_HDi            Glassfish Server, applikationsplattform
18  4xND_QRk_GnJ         Visual Studio, integrerad utvecklingsmiljö
19  56NM_uHB_3am                             Cybersäkerhet, nätverk

                                         headlines
0                  [Styr- och utvecklingsmodeller]
1                        [Applikationsplattformar]
2   [Programmerings- och systemutvecklingsverktyg]
3                        [Kommunikationsprotokoll]
4   [Programmerings- och systemutvecklingsverktyg]
5                        [Applikationsplattformar]
6                                [Kvalitetssystem]
7                             [Övriga kompetenser]
8                             [Övriga kompetenser]
9                        [Kommunikationsprotokoll]
10                       [Applikationsplattformar]
11                       [Integrationsplattformar]
12                                    [Datorspråk]
13                 [Styr- och utvecklingsmodeller]
14                           [Certifikat/licenser]
15                            [Övriga kompetenser]
16                            [Övriga kompetenser]
17                       [Applikationsplattformar]
18  [Programmerings- och systemutvecklingsverktyg]
19                            [Övriga kompetenser]
----------------------------

### Första enkla versionen: naive baseline

In [34]:
# baseline funktionen:
def naive_baseline_extract_skills(text, skills):
    found_skills = []

    text = text.lower()

    for skill in skills:
        if skill.lower() in text:
            found_skills.append(skill)

    return found_skills

In [35]:
# testar baseline på några annonser:
sample_df = df.head(20).copy()

sample_df["naive_baseline_skills"] = sample_df["description"].apply(
    lambda text: naive_baseline_extract_skills(text, skill_names)
)

In [36]:
sample_df[
    ["title", "naive_baseline_skills"]
]

,title,naive_baseline_skills
0,Business Consultant Dynamics 365 Supply Chain ...,[]
1,Hälsoinformatiker för framtidens vårdinformation,"[Informationsmodellering, Förändringsledning, ..."
2,Data Scientist till Innovativt Bolag,[REST]
3,Dynamics 365 Finance Consultant,[]
4,"Enterprise arkitekt, Gävle/Uppsala/Stockholm",[]
5,IT-konsult,[]
6,Senior konsult inom D365 Finance & Operations ...,[]
7,Senior OpenStack-arkitekt,[REST]
8,Lösningsarkitekt,[Webbutveckling]
9,Senior system architect,[]
10,Verksamhetsutvecklare digitalisering,[Förändringsledning]
11,Lösningsarkitekt till offentlig sektor,[]
12,IT-Arkitekt inom IAM,[]
13,Tullverket söker infrastrukturarkitekt contain...,[]
14,Senior Domänarkitekt IT-säkerhet,[]
15,It-infrastrukturarkitekt,[]
16,Lead Solution Architect till vårt Dynamicsteam...,[]
17,ILS Manager,[]
18,Senior Cloud Architect - MS Entra ID,[REST]
19,Senior Kravledare,"[Informationsmodellering, Informationsarkitekt..."

Baseline fungerar tekniskt, men många annonser får inga träffar. Det kan bero på att:
- taxonomin inte innehåller exakt samma formulering som annonsen
- annonsen skriver en förkortning, t.ex. ML istället för Machine Learning
- kompetensen uttrycks på engelska/svenska på annat sätt
- kompetensen finns implicit men inte som exakt fras
- SSYK 2511-listan inte täcker exakt allt som står i varje annons

In [37]:
# undersöker annonser med tomma träffar:
empty_matches = sample_df[
    sample_df["naive_baseline_skills"].apply(len) == 0
]

sample_errors = empty_matches.head(5)

In [38]:
# annonser med empty matches:
sample_errors[
    ["title", "description"]
]

,title,description
0,Business Consultant Dynamics 365 Supply Chain ...,Har du erfarenhet av Dynamics 365 och/eller AX...
3,Dynamics 365 Finance Consultant,Vill du arbeta med den senaste tekniken och hj...
4,"Enterprise arkitekt, Gävle/Uppsala/Stockholm",Lantmäteriet är den myndighet som kartlägger S...
5,IT-konsult,Om jobbet\nCapgemini strävar efter att vara en...
6,Senior konsult inom D365 Finance & Operations ...,Vill du verka som Functional Solution Architec...

In [39]:
# Felanalys som vi kan granska manuellt:
for i, row in sample_errors.iterrows():
    print("\n" + "=" * 80)
    print("TITLE:", row["title"])
    print("NAIVE BASELINE:", row["naive_baseline_skills"])
    
    print("\nDESCRIPTION:")
    print(row["description"])

================================================================================
TITLE: Business Consultant Dynamics 365 Supply Chain Management – Stockholm
NAIVE BASELINE: []

DESCRIPTION:
Har du erfarenhet av Dynamics 365 och/eller AX2012, särskilt inom supply chain management? Vill du hjälpa våra kunder att maximera potentialen i deras D365-lösningar genom att utmana och vägleda dem? Om du är en duktig kommunikatör som vill vara en trusted digital advisor för dina kunder, kan du vara den vi söker
Vad kommer du att göra?I den här rollen kommer du att spela en nyckelroll i att hjälpa våra kunder att maximera potentialen i sina Dynamics 365-lösningar. Du kommer att arbeta nära kunderna för att bygga långsiktiga relationer, förstå deras unika behov och koppla dessa till tekniska möjligheter. Din expertis blir avgörande för att kunderna ska kunna dra full nytta av Microsofts senaste releaser och implementera skräddarsydda lösningar som gör skillnad. Din roll sträcker sig över hela implementationsprocessen – från rådgivning och förfrågningar till att hantera förändringar när kundens verksamhet växer och utvecklas. Du kommer att vara kundens "go-to person", och ditt ansvar blir att identifiera och lösa deras behov genom innovativa och effektiva D365-lösningar. Vårt affärsområde Dynamics är i en spännande tillväxtfas, och vi ser en stark ökning av globala kunder med både utmanande och utvecklande uppdrag. Din arbetsplats? Du kommer att ha din lokala bas på ett av våra kontor i Stockholm, Malmö eller Göteborg. Ditt arbete kommer att vara både varierat och dynamiskt – ibland arbetar du från vårt kontor och ibland är du ute hos kund, där varje dag bjuder på nya utmaningar och möjligheter att göra skillnad. Vem är du? Vi tror att du har cirka tre års erfarenhet av att implementera D365 och/eller AX2012, med särskilt fokus på supply chain management. Du har förmågan att förstå uppgifter både på en strategisk och operativ nivå. Helst ser vi att du har tidigare erfarenhet av rollen som konsult. Du behärskar engelska och svenska flytande då det är språken våra kunder kommunicerar på. Vi söker dig som är kundfokuserad, självständig och som gillar att driva initiativ för våra kunder. Och självklart uppskattar vi om du, precis som vi, tycker att det är viktigt att ha roligt och må bra på jobbet! Ansökan och nästa steg Hos oss kan du ansöka med din LinkedIn och/eller CV och du behöver inte fylla i några långa frågeformulär. I vår rekryteringsprocess tar vi alltid referenser och genomför en bakgrundskontroll innan anställning eller eventuellt erbjudande ges. Intervjuer kommer hållas löpande. Om ColumbusVi har i över 30 år erbjudit kunder digitala lösningar, och för att skryta lite – har vi gjort det väldigt framgångsrikt. Vi är stolta över den feedback vi får av våra kunder. Vår strävan är att bli kundens Trusted Advisor och vi hjälper och vägleder kunden i alla delar av processen. Vi bygger, implementerar och förvaltar affärslösningar, lägger strategi och inspirerar! Summa summarum, så hjälper vi våra kunder att forma lösningar i toppklass efter branschspecifika behov så att de kan nå sin fulla digitala potential. Att ha en god balans mellan arbete och fritid är en självklarhet. Det kan vara allt från hämtning och lämning på förskola till väntan av det där paketet som ska levereras hem ”någon gång mellan 10-19”. Vi lämnar utrymme för återhämtning och ser till att arbeta proaktivt med blicken på horisonten. Dessutom så är vi riktigt bra på att fira framgångar och det är inte ovanligt med fika, lyxfrukost och AW på kontoret  Vi lever efter våra värdeord – Stay Curious, Build Trust, Collaborate och Deliver Customer Success
Jobba på ColumbusSpana in vårt Insta-flöde för att få en bild av hur det är att jobba hos oss genom våra kollegor. Klicka på bilden för att komma till Instagram-kontot. Helt ofiltrerat har vi samlat in omdömen från nuvarande och tidigare kollegor. Klicka nedan för att läsa mer.

================================================================================
TITLE: Dynamics 365 Finance Consultant
NAIVE BASELINE: []

DESCRIPTION:
Vill du arbeta med den senaste tekniken och hjälpa kunder att nå sin fulla potential? Nexer Enterprise Applications söker en driven finanskonsult inom D365 som vill vara en del av ett engagerat och stöttande team. Ta chansen att utvecklas i en flexibel arbetsmiljö där du kan göra verklig skillnad – sök idag! Hur ser rollen ut? Som Finanskonsult arbetar du med att implementera, förbättra eller förvalta Microsoft D365 Finance and Operations för våra kunder. Du driver arbetet kopplat till redovisning och ekonomiska processer, och omvandlar krav till konkreta lösningar för att hjälpa kunderna nyttja systemet till sin fulla potential. Ofta är du en del av ett större leveransteam med experter från olika bakgrunder. Vi tror på styrkan i att varje konsult har fördjupat sig inom ett eller flera områden, vilket gör att det alltid finns hjälpsamma kollegor tillhands vid problem. Du får möjligheter att påverka din karriär och utvecklas inom exempelvis lösningsarkitektur, pre-sales eller som mentor och handledare åt yngre kollegor. Nexer erbjuder en unik kombination av storföretagets stabilitet och den lilla verksamhetens möjlighet att påverka och få saker att hända. Vad kan vi erbjuda dig? En flexibel arbetspolicy, med möjlighet att arbeta hemifrån när det passar dig och ditt team. Ett stöttande team och en organisation som genomsyras av en familjekänsla och mångfald. En rolig arbetsplats där vi älskar att hitta på saker tillsammans. Vi har bl.a. regelbundna spelkvällar, AW:s och träningsutmaningar! Hur är det att arbeta på Nexer Enterprise Applications? På Nexer Enterprise Applications har vi en familjär kultur med en bra sammanhållning i teamen. Arbetsmiljön genomsyras av en kamratlig stämning och ett nära ledarskap. Vi är ett välbekant namn när det gäller Microsoft Dynamics och Microsoft 365 inom Sverige och över hela världen. Du får möjlighet att arbeta inom Sverige och även globalt eftersom det är där våra kunder finns. Vi har en stark vilja att driva affärer och firar våra framgångar genom regelbundna events, resor och konferenser.Här kan du läsa mer om oss: https://nexergroup.com/careerhub/come-on-in-nexer-ea/
Vem är du? Som person gillar du att ta dig an utmaningar och tar initiativ för att hitta den bästa lösningen på ett problem. Vi värdesätter erfarenhet av att arbeta med kunder eller beställare och förmågan att skapa förtroende genom din expertis. Vi söker dig som;
 Är väl bekant med redovisning, ekonomiska principer och ekonomiska processer. Har bred erfarenhet inom D365 F&O eller Dynamics AX. Har genomfört implementationer, inklusive analys, design, konfiguration, testning, utbildning och övergång till förvaltning. Har arbetat med pre-sales, kravanalys eller estimering. Har god kommunikativ förmåga på svenska och engelska i tal och skrift. Ansökan
Du är varmt välkommen att skicka in din ansökan nedan. Vi hanterar ansökningarna löpande, så vänta inte med att söka! #LI-MA2

================================================================================
TITLE: Enterprise arkitekt, Gävle/Uppsala/Stockholm
NAIVE BASELINE: []

DESCRIPTION:
Lantmäteriet är den myndighet som kartlägger Sverige. Till våra uppgifter hör också att registrera och säkra ägandet av alla fastigheter samt hantera deras gränser. Nu söker vi dig som har ett starkt samhällsengagemang. Utveckling och IT utgör en central del av Lantmäteriets verksamhet och är avgörande för vår långsiktiga utveckling. I nära samverkan med övriga verksamhetsområden arbetar vi med strategiska, taktiska och operativa frågor för att säkerställa att våra tekniska lösningar möter både dagens och morgondagens behov. Vi strävar efter att vara en modern myndighet där teknik och samhällsnytta går hand i hand samtidigt som vi erbjuder en kreativ och välkomnande arbetsmiljö. Vi har flera stora intressanta och samhällsviktiga utvecklingsprojekt på gång samt en utveckling av myndighetens digitala infrastruktur. Där behöver vi dig som vill vara med och forma framtiden. 1 plats(er). ARBETSUPPGIFTER
Som enterprisearkitekt kommer du att ingå i ett team på tolv personer som ansvarar för att driva arbetet framåt för hela Lantmäteriet. Dina arbetsuppgifter kommer att sträcka sig från strategisk till operativ nivå och bidra till att utveckla vår arkitektur för att passa in i nuvarande organisation. Du kommer därmed att vara en nybyggare och kommunikatör kring arkitekturfrågor. I rollen kommer du att ansvara för att planera och koordinera arkitekturarbetet och tillsammans med andra arkitekter driva arkitekturarbetet framåt. Du kommer även att ta fram arkitekturkoncept baserat på verksamhetens behov och rekommendera vad som skapar nytta för verksamheten samt bidrar till och utvecklar vår arkitektur. Tillsammans med arkitekturteamet och i samarbete med våra verksamheter, utvecklare och tekniker kommer du att driva arkitekturarbetet framåt. Allt för att säkerställa utformningen av vår arkitektur i syfte att nå Lantmäteriets mål och strategier. I arbetet ingår även att driva och genomföra utredningar och konsekvensanalyser av olika arkitekturalternativ och deras påverkan på vår verksamhet, dess information, organisation och arbetssätt, på både kort och lång sikt. Dina arbetsuppgifter kommer även att innefatta:

	• Arkitekturarbete där du använder modeller för att analysera och dokumentera arkitektur,
	• Skapa underlag för arkitekturella ställningstaganden och alternativa vägval där konsekvenser och förflyttningar av inriktningen analyseras,
	• Driva och leda andra i enterprise- och/eller lösningsarkitekturarbeten,
	• Kommunicera arkitekturer, samt de förflyttningar vi vill göra, till olika intressenter, så att de hamnar i ordinarie förvaltnings- och/eller utvecklingsplaner för genomförande
	• Driva och leda förändringsarbete och skapa förutsättningar för tvärfunktionell samverkan genom målstyrning och mobilisering av grupper och individer
	• Leda och stötta andra arkitekter och leda workshops för modellering

Placering är på Lantmäteriets kontor i Gävle, Uppsala eller Stockholm. Majoriteten av dina kollegor och andra viktiga kontakter är placerade i Gävle varför regelbunden närvaro i Gävle krävs. KVALIFIKATIONER
Vi söker dig som har högskoleutbildning inom teknik/data, eller motsvarande likvärdig erfarenhet, samt mångårig erfarenhet av arbete med IT-arkitektur ur ett lösningsperspektiv. Du har goda kunskaper i utvecklingsprocessen och dess olika steg samt har kännedom om olika ramverk och teknikplattformar. För att nå framgång i rollen krävs även:

	• dokumenterade färdigheter i att genomföra, dokumentera och leda/facilitera ett systematiskt arkitekturarbete,
	• god och bred kunskap om IT-arkitektur, systemintegrationer och teknik,
	• god och bred kunskap av att arbeta med verksamhetsarkitektur, inklusive modellering av processer, och informationsflöden,
	• erfarenhet av att ta fram och implementera målarkitektur, roadmap och arkitekturprinciper,
	• erfarenhet av arbete i portföljstyrning,
	• goda kunskaper i svenska och engelska. Det är meriterande om du har tidigare erfarenhet och förståelse för utveckling av drift av IT-system samt kännedom om privata moln och hybridlösningar riktat mot stora myndigheter, alternativt likande organisationer. Det är även meriterande med tidigare erfarenhet och kunskap om design, utveckling och förvaltning av identitets- och behörighetssystem samt säkerhetslösningar, dvs bred kunskap inom säkerhetsarkitektur. Vi lägger stor vikt vid personliga egenskaper och söker dig som är en lagspelare samt löser problem och utmaningar på ett bra sätt både självständigt och tillsammans med dina kollegor. Du är lyhörd och engagerad och bidrar till ett gott samarbetsklimat. Vidare är du lösningsfokuserad, driven samt har en vilja att kontinuerligt lära dig nya saker. Du är strukturerad och planerar ditt arbete väl och slutför det som påbörjats inom deadline. Du har lätt för att skapa nya och goda relationer och är bekväm i sammanhang där du pratar inför grupp, leder workshops eller agerar facilitator. Du är trygg i dig själv och kan hantera otydlighet i komplexa uppgifter. I tjänsten är det viktigt att du löser problem utan att missa de långsiktiga strategierna. Du har förmågan att se logik och samband i komplex information eller miljö. Tjänsten är säkerhetsklassad vilket innebär att du måste vara svensk medborgare samt att en säkerhetsprövning med tillhörande säkerhetssamtal kommer att göras i samband med anställning. Anställningsform: Tillsvidareanställning. Varaktighet: Tillsvidare, tillträde: Tillträde enligt överenskommelse. Lantmäteriet är i ständig utveckling och det är också alla vi som jobbar här. Våra medarbetare är vår viktigaste resurs för att lyckas med vårt uppdrag. Vi arbetar utifrån det utvecklande medarbetarskapet och vi agerar utifrån den statliga värdegrunden. Som medarbetare på Lantmäteriet ska du kunna förena arbete med fritid och ha en bra balans i livet. När verksamheten tillåter har du bland annat möjlighet att utföra dina arbetsuppgifter till stor del på annan plats än kontoret. Läs mer om vårt erbjudande på lm.se/jobbahososs

För att skicka in din ansökan, klicka på länken i annonsen. Vi arbetar med kompetensbaserad rekrytering och fokuserar på din kompetens för att bedöma dig och andra kandidater objektivt. Vi önskar att du inte bifogar något foto till din ansökan. Du som har skyddade personuppgifter ska inte lägga in din ansökan i vårt rekryteringssystem, istället ber vi dig kontakta rekryterande chef. Vi undanber oss alla erbjudanden om rekryterings- och annonshjälp.

================================================================================
TITLE: IT-konsult
NAIVE BASELINE: []

DESCRIPTION:
Om jobbet
Capgemini strävar efter att vara en lyhörd organisation som verkligen månar om dig som individ och låter dig utvecklas både inom din roll och som person. Låter det stort och opersonligt? Det är det inte. Vi erbjuder snarare det bästa av två världar. Globala muskler lokalt förankrade i svenskt affärsliv, i en familjär gemenskap. Tillsammans sitter vi på en kompetens och projekterfarenhet som få andra kan matcha. Att du kan kontakta vem som helst av dina kollegor i världen med vilken fråga du än har låter som en klyscha, men så ser vardagen ut på Capgemini. Vi är varandras bästa coacher. Arbetsuppgifter:
Som IT-konsult arbetar du i projekt som till exempel kan handla om allt från att ta fram digitala tjänster, implementation av IT-projekt i verksamheten och rena IT- utvecklingsprojekt. Efterfrågad erfarenhet:
Som person är du positiv, utåtriktad och kommunikativ. Du är visionär och samtidigt strukturerad och känner dig bekväm och drivande i dialogen både med kund och ditt projektteam. Vi ser gärna att du har erfarenhet av IT-konsultyrket, erfarenhet av att arbeta i projekt, samt gärna erfarenhet av att arbeta och samverka med olika typer av intressenter - utvecklare, testare, verksamhetsrepresentanter samt styrgrupp.

================================================================================
TITLE: Senior konsult inom D365 Finance & Operations - Malmö
NAIVE BASELINE: []

DESCRIPTION:
Vill du verka som Functional Solution Architect inom D365? Vi har flest projekt inom Dynamics 365 i Norden, och vi växer snabbt – nu vill vi bli ännu fler! Trivs du med att jobba i projekt och utveckla processer och verksamheter? Vill du vara en del av Nordens främsta D365-organisation? Då har vi något spännande för dig! Vi söker en Functional Solution Architect (FSA) med kunskap inom Microsoft Dynamics 365 Finance & Operations. Du kommer att tillhöra ett av våra centrala kontor i Malmö, Göteborg eller Stockholm, men vi erbjuder även möjlighet till remote-arbete, vilket ger dig flexibiliteten att arbeta varifrån du vill. Vad innebär rollen?Som FSA inom Dynamics 365 F&O kommer du att arbeta med både implementation och viss del förvaltning. Din erfarenhet kommer att vara avgörande för att hjälpa våra kunder att optimera sina affärsprocesser. Hos oss är du aldrig ensam – du jobbar tillsammans med ett kompetent team bestående av konsulter, lösningsarkitekter och projektledare. Du kommer att ha en nära dialog med kunderna, där du coachar dem kring deras strategier och hjälper dem att definiera de KPI:er som är avgörande för att styra och utveckla deras verksamhet framåt. I rollen behöver du vara både specialist och rådgivare och därför är det viktigt med systemkunskaper inom D365. Du fördelar din tid mellan kontoret (eller vardagsrummet) och våra kunder tillsammans ditt projektteam, vilket skapar en varierande arbetsmiljö! Vad vi tror om dig:Vi tror att du har flerårig ekonomikunskap på koncernnivå från internationella bolag och förstår kundens hela process. Du har arbetat med Dynamics 365 i ca 3 år
 Du kommunicerar på ett tydligt sätt, både externt och internt
 Du talar och skriver flytande svenska och engelska

Kanske är du ekonom idag och vill jobba med finansprocesser och Dynamics? Eller så är du redan konsult och vill jobba i Nordens ledande Dynamics-organisation med internationella, spännande och komplexa projekt
Vad vi erbjuder dig:
Dynamics har en rad spännande projekt på gång – och fler är på väg! Vi har även sk. ERFA-grupper, både lokala och globala, där vi delar erfarenheter och kompetens för att alltid kunna växa tillsammans. Våra ledare har fått höga betyg i senaste medarbetarundersökningen, och medarbetarnas engagemang är också på topp! Vår kultur kännetecknas av nyfikenhet, kunskap, samarbete och att ha riktigt kul på vägen. Vi erbjuder, utöver en arbetsplats med en personalomsättning lägre än branschens genomsnitt, bl.a: Fast lön + bonus, 30 dagars semester, friskvårdsbidrag på 5000kr/år, privat pensionsförsäkring motsvarande ITP1 samt sjukvårdsförsäkring. Ansökan och nästa steg:Hos oss kan du ansöka med din LinkedIn eller CV och du behöver inte fylla i några långa frågeformulär. Det ska vara smidigt! Vi erbjuder heltidsanställning med tillträde efter överenskommelse. För att göra så objektiva bedömningar som möjligt tillämpar vi logik- och personlighetstester i våra rekryteringsprocesser. Om Columbus:Columbus är ett IT-konsultbolag med ca 1800 medarbetare runtom i världen. Det vi gör allra bäst är utveckling, implementering och underhåll av digitala affärslösningar. Vår uppgift är att guida kunder i deras digitala transformation så att deras företag kan fortsätta att vara framgångsrikt en lång tid framöver. De senaste 30 åren har över 5000 kunder anlitat oss. Det går bra, helt enkelt . Om du frågar oss är hemligheten att vi sitter på ett stort utbud av tekniska lösningar, djup branschkunskap, omfattande teknisk expertis och en rejäl dos kundförståelse. Våra medarbetare är engagerade i sitt arbete och företaget präglas av en stark entreprenörsanda. Detta tack vare de möjligheter som faktiskt finns att vara med och påverka både vår egen och våra kunders verksamhet. Nu behöver vi bli fler och vill ha dig med på färden! Jobba på Columbus:Spana in vårt Insta-flöde för att få en bild av hur det är att jobba hos oss genom våra kollegor. Klicka på bilden för att komma till Instagram-kontot. Helt ofiltrerat har vi samlat in omdömen från nuvarande och tidigare kollegor. Klicka nedan för att läsa mer.

Den enkla baselinen gav inga träffar i flera av annonserna. Vid manuell
granskning innehöll annonserna framför allt generella beskrivningar av
IT-arbete, projektledning, systemutveckling och konsultarbete, erfarenhet av att arbeta i projekt, erfarenhet att arbeta och samverka med olika typer av intressenter - utvecklare, testare men inga tydliga kompetenser som matchade kompetenslistan exakt.

Resultatet bedömmer vi därför som rimligt för dessa exempel.

### Naive baseline på hela träningsdatasetet:

In [40]:
# sammanställer resultatet på hela datasetet och inte endast 20 annonser:

df["naive_baseline_skills"] = df["description"].apply(
    lambda text: naive_baseline_extract_skills(text, skill_names)
)

all_naive_skills = df["naive_baseline_skills"].explode()

naive_skill_counts = all_naive_skills.value_counts()

naive_skill_counts.head(20)

naive_baseline_skills
REST                       798
Informationsarkitektur     136
Förändringsledning         130
Datamodellering            119
Informationsmodellering     92
Informatik                  80
Masterdata                  79
Systemförvaltning           76
Agila arbetsmetoder         54
Verksamhetsanalys           42
API-design                  17
Projektledning, IT          15
Nätverksteknik              14
Prediktiv analys            11
Molnteknik                  10
Datawarehouse                9
Webbutveckling               8
Interaktionsdesign           6
Databasdesign                4
Budgetansvar                 4
Name: count, dtype: int64

`REST = 798` betyder att baseline hittade termen REST i 798 annonser, men vad är REST för något ?

In [41]:
# undersöker i vilka annonser förekommer REST: 
rest_ads = df[
    df["naive_baseline_skills"].apply(lambda x: "REST" in x)
]

rest_ads[["title", "description"]].head()

,title,description
2,Data Scientist till Innovativt Bolag,Är du en analytisk och lösningsorienterad pers...
7,Senior OpenStack-arkitekt,Om företaget\nHos Avaron får du tryggheten i e...
18,Senior Cloud Architect - MS Entra ID,"I rollen blir du expert på att designa, optime..."
27,Solutions Architect till Husqvarna Group!,Som Lösningsarkitekt på Husqvarna Group får du...
34,Senior Kravanalytiker,Senior Kravanalytiker – Produktutveckling inom...

In [42]:
# kollar upp var exakt fångar baseline ordet REST:
row = rest_ads.iloc[0]

print("TITLE:", row["title"])

text = row["description"].lower()

for match in re.finditer("rest", text):
    start = match.start()

    print(
        text[max(0, start - 50): start + 50]
    )
    print("-" * 80)

TITLE: Data Scientist till Innovativt Bolag
et av modeller och kontinuerligt förbättra deras prestanda
delta i hela produktutvecklingsprocessen
--------------------------------------------------------------------------------

In [43]:
# letar genom fler :
for _, row in rest_ads.head(20).iterrows():

    text = row["description"].lower()

    for match in re.finditer("rest", text):
        start = match.start()

        print("\nTITLE:", row["title"])
        print(
            text[max(0, start - 50): start + 50]
        )
        print("-" * 80)

TITLE: Data Scientist till Innovativt Bolag
et av modeller och kontinuerligt förbättra deras prestanda
delta i hela produktutvecklingsprocessen
--------------------------------------------------------------------------------

TITLE: Senior OpenStack-arkitekt
ingsregler och interna riktlinjer. du analyserar prestanda och kapacitet samt driver förbättringar s
--------------------------------------------------------------------------------

TITLE: Senior Cloud Architect - MS Entra ID
pande iam-strategier för att säkerställa optimal prestanda, skalbarhet och säkerhet i azure-miljön.
--------------------------------------------------------------------------------

TITLE: Solutions Architect till Husqvarna Group!
 för professionella användare. de för samman hög prestanda, användarvänlighet och säkerhet och erbju
--------------------------------------------------------------------------------

TITLE: Senior Kravanalytiker
ionella och icke-funktionella krav kopplade till prestanda, användarvänlighet och skalbarhet
arbeta
--------------------------------------------------------------------------------

TITLE: Vi förstärker vår IT-arkitektfunktion
god samarbetsförmåga. du är kommunikativ, aktiv, prestigelös och trivs i en föränderlig och komplex
--------------------------------------------------------------------------------

TITLE: Cloud Platform Architect
 du får ett stort inflytande över norion banks azurestrategi och arkitektur. vidare kommer du att sa
--------------------------------------------------------------------------------

TITLE: Cloud Platform Architect
 monitorering och automatisering. designa säkra, prestandaoptimerade drift och nätverkslösningar (hu
--------------------------------------------------------------------------------

TITLE: IT-arkitekt/ Techlead
ett förmånskort som kan användas i butiker och på restauranger. vid goda resultat delas även en resu
--------------------------------------------------------------------------------

TITLE: Systemingenjör
onsarbete av system. kunskap om fartyg och sensorprestanda. erfarenhet av kravhantering och verifier
--------------------------------------------------------------------------------

TITLE: BI Engineer
r someone who is collaborative and organized, interested to work with people and understand their da
--------------------------------------------------------------------------------

TITLE: Lösningsarkitekt för området Informationshantering
ör utvecklingsverksamhetens framtid. för att våra resterande team ska ha möjlighet att ta stora steg
--------------------------------------------------------------------------------

TITLE: Senior Solution Architect  sökes till Iver
r för både process och resultat, och trivs i ett prestigelöst samarbete med andra. samtidigt är du s
--------------------------------------------------------------------------------

TITLE: Lösningsarkitekt till Softhouse i Luleå
tiga softhouse-kollegor. stämningen är öppen och prestigelös där vi delar med oss av kunskap och erf
--------------------------------------------------------------------------------

TITLE: System Architect - Hardware
ka i val av hårdvarukomponenter för att optimera prestanda och tillförlitlighet

rollen innebär viss
--------------------------------------------------------------------------------

TITLE: Infrastructure Specialist till Turnpikes
takter och bidra till förbättringar av systemens prestanda och säkerhet. vi tillämpar löpande urval
--------------------------------------------------------------------------------

TITLE: Kravanalytiker / Processanalytiker
at till tre processområden:
utbildningsprocessen
prestationsprocessen
successionsprocessen

kravanal
--------------------------------------------------------------------------------

TITLE: Lösningsarkitekt
 till att lösningens kvalitetsegenskaper – såsom prestanda, skalbarhet, robusthet, förvaltningsbarhe
--------------------------------------------------------------------------------

TITLE: Junior systemutvecklare C#/.NET & Sharepoint
a både kod och arbetsprocesser. du är ödmjuk och prestigelös, är lyhörd för feedback och ser samarbe
--------------------------------------------------------------------------------

TITLE: Lösningsarkitekt Informationshantering med slutanvändarfokus
h initiativrik. för oss är det viktigt att du är prestigelös och positiv, att vi hjälps åt mot ett g
--------------------------------------------------------------------------------

TITLE: Lösningsarkitekt till Softhouse i Luleå
tiga softhouse-kollegor. stämningen är öppen och prestigelös där vi delar med oss av kunskap och erf
--------------------------------------------------------------------------------

Den första implementationen använde enkel substring-matchning. Det innebär
att en kompetens kan identifieras även när tecknen endast förekommer som en
del av ett annat ord (exempel: pRESTanda, pRESTigelös).

Ett tydligt exempel var kompetensen `REST`, som fick ett mycket stort antal
träffar. Vid manuell granskning kunde flera falska positiva träffar
identifieras, exempelvis när bokstavskombinationen förekom inuti andra ord.

Baselinen justerades därför till matchning med tydliga ordgränser.

### Riktiga baseline:

In [44]:
# förbättrad baseline: 
def baseline_extract_skills(text, skills):
    found_skills = []

    text = text.lower()

    for skill in skills:
        pattern = r"\b" + re.escape(skill.lower()) + r"\b"

        if re.search(pattern, text):
            found_skills.append(skill)

    return found_skills

In [45]:
# testar riktiga baselinen på samma 20 annonser:
sample_df["baseline_skills"] = sample_df["description"].apply(
    lambda text: baseline_extract_skills(text, skill_names)
)

In [46]:
sample_df[
    [
        "title",
        "naive_baseline_skills",
        "baseline_skills"
    ]
]

,title,naive_baseline_skills,baseline_skills
0,Business Consultant Dynamics 365 Supply Chain ...,[],[]
1,Hälsoinformatiker för framtidens vårdinformation,"[Informationsmodellering, Förändringsledning, ...","[Informationsmodellering, Förändringsledning, ..."
2,Data Scientist till Innovativt Bolag,[REST],[]
3,Dynamics 365 Finance Consultant,[],[]
4,"Enterprise arkitekt, Gävle/Uppsala/Stockholm",[],[]
5,IT-konsult,[],[]
6,Senior konsult inom D365 Finance & Operations ...,[],[]
7,Senior OpenStack-arkitekt,[REST],[]
8,Lösningsarkitekt,[Webbutveckling],[Webbutveckling]
9,Senior system architect,[],[]
10,Verksamhetsutvecklare digitalisering,[Förändringsledning],[Förändringsledning]
11,Lösningsarkitekt till offentlig sektor,[],[]
12,IT-Arkitekt inom IAM,[],[]
13,Tullverket söker infrastrukturarkitekt contain...,[],[]
14,Senior Domänarkitekt IT-säkerhet,[],[]
15,It-infrastrukturarkitekt,[],[]
16,Lead Solution Architect till vårt Dynamicsteam...,[],[]
17,ILS Manager,[],[]
18,Senior Cloud Architect - MS Entra ID,[REST],[]
19,Senior Kravledare,"[Informationsmodellering, Informationsarkitekt...","[Informationsmodellering, Informationsarkitekt..."

In [47]:
# kör riktiga baselinen på hela train_set:
df["baseline_skills"] = df["description"].apply(
    lambda text: baseline_extract_skills(text, skill_names)
)

In [48]:
# räknar kompetenser för den slutliga baselinen:
all_baseline_skills = df["baseline_skills"].explode()

baseline_skill_counts = all_baseline_skills.value_counts()

baseline_skill_counts.head(20)

baseline_skills
Informationsarkitektur     136
Förändringsledning         130
Datamodellering            116
Informationsmodellering     92
REST                        68
Masterdata                  66
Informatik                  60
Systemförvaltning           59
Agila arbetsmetoder         54
Verksamhetsanalys           38
API-design                  17
Projektledning, IT          15
Prediktiv analys            11
Webbutveckling               8
Nätverksteknik               8
Datawarehouse                7
Interaktionsdesign           5
Databasdesign                4
Budgetansvar                 4
Molnteknik                   4
Name: count, dtype: int64

In [49]:
# jämför de två versionerna: 
comparison = pd.DataFrame({
    "naive_baseline": skill_counts,
    "baseline": baseline_skill_counts
}).fillna(0)

comparison.head(20)

                                                    naive_baseline  baseline
baseline_skills
API-design                                                      17      17.0
Agila arbetsmetoder                                             54      54.0
Automationsteknik                                                1       1.0
Budgetansvar                                                     4       4.0
Databasdesign                                                    4       4.0
Datamodellering                                                119     116.0
Datawarehouse                                                    9       7.0
Design Thinking                                                  2       2.0
Förändringsledning                                             130     130.0
Informatik                                                      80      60.0
Informationsarkitektur                                         136     136.0
Informationsmodellering                                         92      92.0
Interaktionsdesign                                               6       5.0
Kravhantering, systemutveckling                                  2       2.0
Masterdata                                                      79      66.0
Medieteknik                                                      2       2.0
Microsoft Certified: Azure Administrator Associate               1       1.0
Molnteknik                                                      10       4.0
Nätverksdesign                                                   3       3.0
Nätverksteknik                                                  14       8.0

Den ursprungliga naiva baselinen använde enkel substring-matchning, vilket gav falska positiva träffar. Ett tydligt exempel var kompetensen REST, som bland annat matchades i ordet "prestigelös" och en del av andra ord. 
Efter att matchningen förbättrades med reguljära uttryck och ordgränser minskade REST från 798 till 68 träffar, medan flera andra kompetenser behöll samma antal träffar. Detta tyder på att den förbättrade baselinen minskar antalet falska positiva matchningar.

Den justerade versionen används därför som projektets baseline.

## Sammanfattning av baseline

Projektets baseline bygger på regelbaserad matchning mellan kompetenser från
Arbetsförmedlingens SSYK 2511-taxonomi och jobbannonsernas beskrivningar.

Den första naiv implementation använde substring-matchning. Den användes för
att identifiera problem med falska positiva träffar, exempelvis när korta
kompetenstermer förekom som delar av andra ord.

Den slutliga baselinen använder därför tydligare ordavgränsning vid
matchningen. Metoden fungerar som en enkel referensmetod men är fortfarande
begränsad eftersom den kan missa exempelvis förkortningar, synonymer och
alternativa formuleringar.

Baselinen och resultatet kommer därför senare att utvecklas på träningsdata och utvärderas på det
separata manuellt annoterade test-setet tillsammans med projektets NLP-metoder.